import test from 'node:test';
import assert from 'node:assert/strict';
import {captureVideoFrame, createInstantReplayController, createRecordingController, recordingMimeTypesForPreference, supportedRecordingMimeTypes} from './capture.mjs';

test('recording preferences prioritize the requested codec and retain safe fallbacks', () => { assert.equal(recordingMimeTypesForPreference('VP9')[0], 'video/webm;codecs=vp9,opus'); assert.equal(recordingMimeTypesForPreference('H.264')[0], 'video/mp4;codecs=avc1.42E01E,mp4a.40.2'); assert.deepEqual(recordingMimeTypesForPreference('unknown'), recordingMimeTypesForPreference('Automatic')); });

test('recording controller selects a supported MIME type and returns a Blob', async () => { let instance; class FakeRecorder { static isTypeSupported(type) { return type === 'video/webm'; } constructor(stream, options) { instance = this; this.stream = stream; this.options = options; } start() { this.ondataavailable?.({data: new Blob(['frame'])}); } stop() { this.onstop?.(); } } const controller = createRecordingController({stream: {id: 'stream'}, MediaRecorderImpl: FakeRecorder}); assert.deepEqual(supportedRecordingMimeTypes({MediaRecorderImpl: FakeRecorder}), ['video/webm']); controller.start(); assert.equal(controller.state, 'recording'); const blob = await controller.stop(); assert.equal(controller.state, 'stopped'); assert.equal(blob.type, 'video/webm'); });
test('recording controller honors a preferred codec when the browser supports it', () => { let options; class FakeRecorder { static isTypeSupported(type) { return type === 'video/mp4;codecs=avc1.42E01E,mp4a.40.2'; } constructor(stream, value) { options = value; } start() {} } const controller = createRecordingController({stream: {id: 'stream'}, codec: 'H.264', MediaRecorderImpl: FakeRecorder}); controller.start(); assert.deepEqual(options, {mimeType: 'video/mp4;codecs=avc1.42E01E,mp4a.40.2'}); });
test('recording controller fails clearly without a stream or recorder', () => { assert.throws(() => createRecordingController({}), /MediaStream/); });
test('instant replay keeps a bounded rolling buffer and returns a local clip', () => { let instance; class FakeRecorder { static isTypeSupported(type) { return type === 'video/webm'; } constructor(stream, options) { instance = this; this.stream = stream; this.options = options; } start(timeslice) { this.timeslice = timeslice; for (let index = 0; index < 18; index += 1) this.ondataavailable?.({data: new Blob([String(index)])}); } stop() { this.onstop?.(); } } const controller = createInstantReplayController({stream: {id: 'stream'}, durationSeconds: 15, MediaRecorderImpl: FakeRecorder}); controller.start(); assert.equal(instance.timeslice, 1000); assert.equal(controller.state, 'recording'); assert.equal(controller.bufferedChunks, 16); const clip = controller.clip(); assert.equal(clip.type, 'video/webm'); assert.equal(clip.size > 0, true); controller.stop(); assert.equal(controller.state, 'stopped'); });
test('screenshot capture draws the current video frame to a PNG blob', async () => { let drawn = false; const video = {videoWidth: 1280, videoHeight: 720}; const documentLike = {createElement: () => ({getContext: () => ({drawImage: () => {drawn = true;}}), toBlob: null})}; documentLike.createElement = () => { const canvas = {width: 0, height: 0, getContext: () => ({drawImage: () => {drawn = true;}})}; canvas.toBlob = callback => callback(new Blob(['png'], {type: 'image/png'})); return canvas; }; const blob = await captureVideoFrame(video, {documentLike}); assert.equal(drawn, true); assert.equal(blob.type, 'image/png'); });
