import assert from 'node:assert/strict';
import {mkdtemp, mkdir, writeFile, rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import {createInstalledAdapterRuntime} from './adapter-runtime.mjs';

const manifest = {id: 'linux-input', version: '1.0.0', platform: 'linux', format: 'directory', signature: {algorithm: 'ECDSA-P256-SHA256', signer: 'test', value: 'signed'}, files: [{path: 'adapter.mjs', type: 'file', sizeBytes: 1, integrity: 'sha256-file'}], entrypoint: 'adapter.mjs'};

test('installed adapter runtime verifies pointer, package, platform, and factory before activation', async () => { const root = await mkdtemp(join(tmpdir(), 'spartan-adapter-')); try { const target = join(root, 'linux-input', '1.0.0'); await mkdir(target, {recursive: true}); await writeFile(join(root, 'linux-input', 'current.json'), JSON.stringify({id: 'linux-input', version: '1.0.0', integrity: 'sha256-file'})); await writeFile(join(target, 'manifest.json'), JSON.stringify(manifest)); const runtime = createInstalledAdapterRuntime({installRoot: root, id: 'linux-input', platform: 'linux', verifyManifest: async ({manifest: value}) => value.signature.signer === 'test', loadModule: async () => ({createPlatformAdapter: async ({platform, kind}) => ({platform, kind, execute() {}})})}); const loaded = await runtime.load(); assert.equal(loaded.adapter.platform, 'linux'); assert.equal((await runtime.inspect()).manifest.entrypoint, 'adapter.mjs'); const activated = await runtime.createBoundary({registry: {get: () => ({state: 'ready'}), describe: () => ({})}, kind: 'input'}); assert.equal(activated.adapter.platform, 'linux'); await activated.boundary.invoke('input', 'execute', {kind: 'button'}); } finally { await rm(root, {recursive: true, force: true}); } });
test('installed adapter runtime fails closed for an unverified manifest', async () => { const root = await mkdtemp(join(tmpdir(), 'spartan-adapter-')); try { const target = join(root, 'linux-input', '1.0.0'); await mkdir(target, {recursive: true}); await writeFile(join(root, 'linux-input', 'current.json'), JSON.stringify({id: 'linux-input', version: '1.0.0'})); await writeFile(join(target, 'manifest.json'), JSON.stringify(manifest)); const runtime = createInstalledAdapterRuntime({installRoot: root, id: 'linux-input', platform: 'linux', verifyManifest: async () => false, loadModule: async () => { throw new Error('must not load'); }}); await assert.rejects(() => runtime.load(), /verification failed/); } finally { await rm(root, {recursive: true, force: true}); } });
test('installed virtual-gamepad runtime verifies and loads its dedicated factory', async () => { const root = await mkdtemp(join(tmpdir(), 'spartan-adapter-')); try { const virtualManifest = {...manifest, id: 'windows-virtual-gamepad', kind: 'virtual-gamepad', platform: 'win32'}; const target = join(root, virtualManifest.id, virtualManifest.version); await mkdir(target, {recursive: true}); await writeFile(join(root, virtualManifest.id, 'current.json'), JSON.stringify({id: virtualManifest.id, version: virtualManifest.version, integrity: 'sha256-file'})); await writeFile(join(target, 'manifest.json'), JSON.stringify(virtualManifest)); const runtime = createInstalledAdapterRuntime({installRoot: root, id: virtualManifest.id, platform: 'win32', expectedKind: 'virtual-gamepad', verifyManifest: async () => true, loadModule: async () => ({createVirtualGamepad: async ({platform, kind}) => ({platform, kind, execute() {}})})}); const loaded = await runtime.load(); assert.equal(loaded.manifest.kind, 'virtual-gamepad'); assert.equal(loaded.adapter.platform, 'win32'); assert.equal(loaded.adapter.kind, 'virtual-gamepad'); await assert.rejects(() => runtime.createBoundary(), /virtual-gamepad adapters/); } finally { await rm(root, {recursive: true, force: true}); } });
