import assert from 'node:assert/strict';
import {mkdtemp, mkdir, writeFile, rm} from 'node:fs/promises';
import {join} from 'node:path';
import test from 'node:test';
import {createInstalledAdapterRuntime} from './adapter-runtime.mjs';

const manifest = {id: 'linux-input', version: '1.0.0', platform: 'linux', format: 'directory', signature: {algorithm: 'ECDSA-P256-SHA256', signer: 'test', value: 'signed'}, files: [{path: 'adapter.mjs', type: 'file', sizeBytes: 1, integrity: 'sha256-file'}], entrypoint: 'adapter.mjs'};

test('installed adapter runtime verifies pointer, package, platform, and factory before activation', async () => { const root = await mkdtemp('/tmp/spartan-adapter-'); try { const target = join(root, 'linux-input', '1.0.0'); await mkdir(target, {recursive: true}); await writeFile(join(root, 'linux-input', 'current.json'), JSON.stringify({id: 'linux-input', version: '1.0.0', integrity: 'sha256-file'})); await writeFile(join(target, 'manifest.json'), JSON.stringify(manifest)); const runtime = createInstalledAdapterRuntime({installRoot: root, id: 'linux-input', platform: 'linux', verifyManifest: async ({manifest: value}) => value.signature.signer === 'test', loadModule: async () => ({createPlatformAdapter: async ({platform}) => ({platform, execute() {}})})}); const loaded = await runtime.load(); assert.equal(loaded.adapter.platform, 'linux'); assert.equal((await runtime.inspect()).manifest.entrypoint, 'adapter.mjs'); } finally { await rm(root, {recursive: true, force: true}); } });
test('installed adapter runtime fails closed for an unverified manifest', async () => { const root = await mkdtemp('/tmp/spartan-adapter-'); try { const target = join(root, 'linux-input', '1.0.0'); await mkdir(target, {recursive: true}); await writeFile(join(root, 'linux-input', 'current.json'), JSON.stringify({id: 'linux-input', version: '1.0.0'})); await writeFile(join(target, 'manifest.json'), JSON.stringify(manifest)); const runtime = createInstalledAdapterRuntime({installRoot: root, id: 'linux-input', platform: 'linux', verifyManifest: async () => false, loadModule: async () => { throw new Error('must not load'); }}); await assert.rejects(() => runtime.load(), /verification failed/); } finally { await rm(root, {recursive: true, force: true}); } });
