import test from 'node:test';
import assert from 'node:assert/strict';
import {detectHostEnvironment, detectHostRuntime} from './environment.mjs';
import {normalizeHostConfig, readHostConfig} from './config.mjs';

test('host environment detection is deterministic with injected probes', () => { const environment = detectHostEnvironment({platformName: 'linux', releaseName: 'test', commandProbe: command => command === 'ffmpeg'}); assert.equal(environment.adapter.id, 'linux-pipewire'); assert.equal(environment.tools.ffmpeg, true); assert.equal(environment.tools.gstreamer, false); assert.equal(environment.readiness.mediaEncode, true); assert.equal(environment.readiness.osInput, false); });
test('unsupported platforms fail closed', () => { const environment = detectHostEnvironment({platformName: 'ios', commandProbe: () => false}); assert.equal(environment.adapter, null); assert.equal(environment.readiness.mediaEncode, false); });
test('host runtime discovery advertises installed native capabilities without serializing bindings', async () => { const runtime = await detectHostRuntime({platformName: 'linux', commandProbe: () => false, packageName: '@test/linux', loader: async () => ({createBindings: async () => ({platform: 'linux', capabilities: {capture: true, audio: true, gamepad: true, virtualGamepad: true, input: true}, input: {execute() {}}})})}); assert.equal(runtime.environment.nativeBinding.status, 'available'); assert.equal(runtime.environment.readiness.osInput, true); assert.equal(runtime.environment.inputAdapter.gamepad, true); assert.equal(runtime.environment.inputAdapter.virtualGamepad, true); assert.equal(runtime.environment.platformAdapters.adapters.input.state, 'ready'); assert.equal(runtime.environment.platformAdapters.adapters.capture.state, 'ready'); assert.equal(runtime.environment.nativeBinding.capabilities.capture, true); assert.equal(runtime.environment.bindings, undefined); assert.equal(typeof runtime.bindings.input.execute, 'function'); });
test('host runtime discovery fails closed when the optional package is absent', async () => { const runtime = await detectHostRuntime({platformName: 'linux', loader: async () => { const error = new Error('missing'); error.code = 'ERR_MODULE_NOT_FOUND'; throw error; }}); assert.equal(runtime.environment.nativeBinding.status, 'unavailable'); assert.equal(runtime.environment.readiness.osInput, false); assert.equal(runtime.bindings, null); });
test('host runtime composes an optional virtual-gamepad package with the native input boundary', async () => { const runtime = await detectHostRuntime({platformName: 'win32', packageName: '@test/windows', loader: async () => ({createBindings: async () => ({platform: 'win32', capabilities: {keyboard: true, pointer: true}, input: {execute: async () => {}}})}), virtualGamepadPackageName: '@test/windows-driver', virtualGamepadLoader: async () => ({createVirtualGamepad: async () => ({platform: 'win32', execute: async () => {}})})}); assert.equal(runtime.environment.virtualGamepadBinding.status, 'available'); assert.equal(runtime.environment.inputAdapter.virtualGamepad, true); assert.equal(runtime.environment.readiness.osInput, true); assert.equal(typeof runtime.bindings.input.execute, 'function'); });
test('host runtime reports configured but unavailable external driver readiness', async () => { const runtime = await detectHostRuntime({platformName: 'win32', virtualGamepadBackend: 'Windows external driver', virtualGamepadPackageName: '@test/missing', virtualGamepadLoader: async () => { const error = new Error('missing'); error.code = 'ERR_MODULE_NOT_FOUND'; throw error; }}); assert.equal(runtime.environment.virtualGamepadConfig.backend, 'Windows external driver'); assert.equal(runtime.environment.virtualGamepadBinding.readiness.state, 'unavailable'); assert.equal(runtime.environment.readiness.virtualGamepad, false); });
test('host configuration files normalize controller and runtime settings without secrets', () => { const config = normalizeHostConfig({platform: 'win32', hostId: 'living-room', virtualGamepadBackend: 'Windows external driver', virtualGamepadPackage: '@spartan/windows-driver', virtualGamepadDevice: 'xinput-0', enableInput: true, allowedOrigins: ['https://play.example']}, {platform: 'win32'}); assert.equal(config.hostId, 'living-room'); assert.equal(config.virtualGamepad.packageName, '@spartan/windows-driver'); assert.equal(config.enableInput, true); assert.throws(() => normalizeHostConfig({pairingCode: 'secret'}, {platform: 'linux'}), /cannot be stored/); });
test('host configuration reader rejects malformed files and accepts injected files', () => { const config = readHostConfig('/config.json', {platform: 'darwin', readFile: () => JSON.stringify({virtualGamepadBackend: 'macOS external driver', virtualGamepadDevice: 'dualshock-1'})}); assert.equal(config.virtualGamepadDevice, 'dualshock-1'); assert.throws(() => readHostConfig('/bad.json', {readFile: () => '{'}), /valid JSON/); });
