import test from 'node:test';
import assert from 'node:assert/strict';
import {detectHostEnvironment, detectHostRuntime} from './environment.mjs';
import {createHostMediaPolicy, createHostRuntimePolicy, normalizeHostConfig, readHostConfig} from './config.mjs';

test('host environment detection is deterministic with injected probes', () => { const environment = detectHostEnvironment({platformName: 'linux', releaseName: 'test', commandProbe: command => command === 'ffmpeg'}); assert.equal(environment.adapter.id, 'linux-pipewire'); assert.equal(environment.tools.ffmpeg, true); assert.equal(environment.tools.gstreamer, false); assert.equal(environment.readiness.mediaEncode, true); assert.equal(environment.readiness.osInput, false); });
test('unsupported platforms fail closed', () => { const environment = detectHostEnvironment({platformName: 'ios', commandProbe: () => false}); assert.equal(environment.adapter, null); assert.equal(environment.readiness.mediaEncode, false); });
test('unsupported host runtimes retain a control-plane-only profile', async () => { const runtime = await detectHostRuntime({platformName: 'android', commandProbe: () => false}); assert.equal(runtime.environment.platform, 'android'); assert.equal(runtime.environment.virtualGamepadBinding.readiness.state, 'not-required'); assert.equal(runtime.environment.readiness.osInput, false); assert.equal(runtime.bindings, null); });
test('host runtime discovery advertises installed native capabilities without serializing bindings', async () => { const runtime = await detectHostRuntime({platformName: 'linux', commandProbe: () => false, packageName: '@test/linux', loader: async () => ({createBindings: async () => ({platform: 'linux', capabilities: {capture: true, audio: true, gamepad: true, virtualGamepad: true, input: true}, input: {execute() {}}})})}); assert.equal(runtime.environment.nativeBinding.status, 'available'); assert.equal(runtime.environment.readiness.osInput, true); assert.equal(runtime.environment.inputAdapter.gamepad, true); assert.equal(runtime.environment.inputAdapter.virtualGamepad, true); assert.equal(runtime.environment.platformAdapters.adapters.input.state, 'ready'); assert.equal(runtime.environment.platformAdapters.adapters.capture.state, 'ready'); assert.equal(runtime.environment.nativeBinding.capabilities.capture, true); assert.equal(runtime.environment.bindings, undefined); assert.equal(typeof runtime.bindings.input.execute, 'function'); });
test('host runtime discovery fails closed when the optional package is absent', async () => { const runtime = await detectHostRuntime({platformName: 'linux', loader: async () => { const error = new Error('missing'); error.code = 'ERR_MODULE_NOT_FOUND'; throw error; }}); assert.equal(runtime.environment.nativeBinding.status, 'unavailable'); assert.equal(runtime.environment.readiness.osInput, false); assert.equal(runtime.bindings, null); });
test('host runtime composes an optional virtual-gamepad package with the native input boundary', async () => { const runtime = await detectHostRuntime({platformName: 'win32', packageName: '@test/windows', loader: async () => ({createBindings: async () => ({platform: 'win32', capabilities: {keyboard: true, pointer: true}, input: {execute: async () => {}}})}), virtualGamepadPackageName: '@test/windows-driver', virtualGamepadLoader: async () => ({createVirtualGamepad: async () => ({platform: 'win32', execute: async () => {}})})}); assert.equal(runtime.environment.virtualGamepadBinding.status, 'available'); assert.equal(runtime.environment.inputAdapter.virtualGamepad, true); assert.equal(runtime.environment.readiness.osInput, true); assert.equal(typeof runtime.bindings.input.execute, 'function'); });
test('host runtime reports configured but unavailable external driver readiness', async () => { const runtime = await detectHostRuntime({platformName: 'win32', virtualGamepadBackend: 'Windows external driver', virtualGamepadPackageName: '@test/missing', virtualGamepadLoader: async () => { const error = new Error('missing'); error.code = 'ERR_MODULE_NOT_FOUND'; throw error; }}); assert.equal(runtime.environment.virtualGamepadConfig.backend, 'Windows external driver'); assert.equal(runtime.environment.virtualGamepadBinding.readiness.state, 'unavailable'); assert.equal(runtime.environment.readiness.virtualGamepad, false); });
test('host runtime keeps an explicitly disabled virtual gamepad unavailable', async () => { const runtime = await detectHostRuntime({platformName: 'linux', virtualGamepadBackend: 'Disabled', packageName: '@test/linux', loader: async () => ({createBindings: async () => ({platform: 'linux', capabilities: {input: true, gamepad: true, virtualGamepad: true}, input: {execute: async () => {}}})})}); assert.equal(runtime.environment.virtualGamepadBinding.readiness.state, 'not-required'); assert.equal(runtime.environment.readiness.virtualGamepad, false); });
test('host runtime does not infer an external driver from native input capabilities', async () => { const runtime = await detectHostRuntime({platformName: 'linux', virtualGamepadBackend: 'Windows external driver', packageName: '@test/linux', loader: async () => ({createBindings: async () => ({platform: 'linux', capabilities: {input: true, gamepad: true, virtualGamepad: true}, input: {execute: async () => {}}})})}); assert.equal(runtime.environment.virtualGamepadConfig.compatible, false); assert.equal(runtime.environment.virtualGamepadBinding.readiness.state, 'unavailable'); assert.equal(runtime.environment.readiness.virtualGamepad, false); });
test('host configuration files normalize controller and runtime settings without secrets', () => { const config = normalizeHostConfig({platform: 'win32', hostId: 'living-room', captureSource: 'Primary display', videoCodec: 'VP9', maxResolution: '1440p', maxFramerate: '120 FPS', captureSystemAudio: false, captureMicrophone: true, audioCodec: 'Opus', controllerPolicy: {defaultProfile: 'PlayStation layout', playerSlots: 99, allowHid: true}, virtualGamepadBackend: 'Windows external driver', virtualGamepadPackage: '@spartan/windows-driver', virtualGamepadDevice: 'xinput-0', virtualGamepadDevices: ['xinput-0', 'xinput-1'], enableInput: true, requireExplicitPairing: false, wakeOnLan: true, logLevel: 'Verbose', allowedOrigins: ['https://play.example']}, {platform: 'win32'}); assert.equal(config.hostId, 'living-room'); assert.equal(config.captureSource, 'Primary display'); assert.equal(config.videoCodec, 'VP9'); assert.equal(config.maxResolution, '1440p'); assert.equal(config.maxFramerate, '120 FPS'); assert.equal(config.captureSystemAudio, false); assert.equal(config.captureMicrophone, true); assert.equal(config.audioCodec, 'Opus'); assert.equal(config.virtualGamepad.packageName, '@spartan/windows-driver'); assert.deepEqual(config.virtualGamepadDevices, ['xinput-0', 'xinput-1']); assert.equal(config.controllerPolicy.defaultProfile, 'PlayStation layout'); assert.equal(config.controllerPolicy.playerSlots, 8); assert.equal(config.controllerPolicy.allowHid, true); assert.equal(config.enableInput, true); assert.equal(config.requireExplicitPairing, false); assert.equal(config.wakeOnLan, true); assert.equal(config.logLevel, 'Verbose'); assert.throws(() => normalizeHostConfig({pairingCode: 'secret'}, {platform: 'linux'}), /cannot be stored/); });
test('host configuration reader rejects malformed files and accepts injected files', () => { const config = readHostConfig('/config.json', {platform: 'darwin', readFile: () => JSON.stringify({virtualGamepadBackend: 'macOS external driver', virtualGamepadDevice: 'dualshock-1'})}); assert.equal(config.virtualGamepadDevice, 'dualshock-1'); assert.throws(() => readHostConfig('/bad.json', {readFile: () => '{'}), /valid JSON/); });
test('host configuration reader permits unsupported control-plane hosts without native controller claims', () => { const config = readHostConfig(undefined, {platform: 'android'}); assert.equal(config.platform, 'android'); assert.equal(config.virtualGamepad.backend, 'Disabled'); assert.equal(config.virtualGamepad.compatible, true); });
test('host runtime policy exposes bounded non-secret media and lifecycle settings', () => { const config = normalizeHostConfig({platform: 'linux', captureSource: 'Selected window', videoCodec: 'VP9', maxResolution: '1440p', maxFramerate: '120 FPS', captureSystemAudio: false, captureMicrophone: true, audioCodec: 'Opus', enableNativeMedia: true, enableNativeAudio: true, enableInput: false, requireExplicitPairing: false, wakeOnLan: true, logLevel: 'Verbose'}, {platform: 'linux'}); assert.deepEqual(createHostRuntimePolicy(config), {captureSource: 'Selected window', videoCodec: 'VP9', maxResolution: '1440p', maxFramerate: '120 FPS', captureSystemAudio: false, captureMicrophone: true, audioCodec: 'Opus', enableNativeMedia: true, enableNativeAudio: true, enableInput: false, requireExplicitPairing: false, wakeOnLan: true, logLevel: 'Verbose'}); });
test('host media policy resolves bounded native codec and display parameters', () => { const config = normalizeHostConfig({platform: 'win32', videoCodec: 'HEVC', maxResolution: '4K', maxFramerate: '144 FPS', audioCodec: 'AAC'}, {platform: 'win32'}); assert.deepEqual(createHostMediaPolicy(config), {...createHostRuntimePolicy(config), width: 3840, height: 2160, framerate: 144, videoCodec: 'h264', audioCodec: 'aac'}); });
