import assert from 'node:assert/strict';
import test from 'node:test';
import {createNativeHostSession} from './native-session.mjs';

function component(log, name, fail = false) { return {state: 'unconfigured', capabilities: {state: 'unconfigured'}, async start() { log.push(`${name}:start`); if (fail) throw new Error(`${name} failed`); this.state = 'active'; this.capabilities = {state: 'active'}; }, async stop() { log.push(`${name}:stop`); this.state = 'stopped'; this.capabilities = {state: 'stopped'}; }}; }

test('native host session starts media and audio transactionally and routes input', async () => { const log = []; const media = component(log, 'media'); const audio = component(log, 'audio'); const events = []; const session = createNativeHostSession({platform: 'linux', mediaPublisher: media, audioPublisher: audio, inputExecutor: {state: 'ready', dispatch: event => { events.push(event); return 'accepted'; }, close: () => log.push('input:close')}}); await session.start(); assert.equal(session.state, 'active'); assert.deepEqual(await session.dispatchInput({kind: 'button'}), 'accepted'); assert.deepEqual(events, [{kind: 'button'}]); await session.stop(); assert.deepEqual(log, ['media:start', 'audio:start', 'input:close', 'audio:stop', 'media:stop']); });
test('native host session rolls media back when audio startup fails', async () => { const log = []; const session = createNativeHostSession({platform: 'win32', mediaPublisher: component(log, 'media'), audioPublisher: component(log, 'audio', true)}); await assert.rejects(() => session.start(), /audio failed/); assert.equal(session.state, 'failed'); assert.deepEqual(log, ['media:start', 'audio:start', 'media:stop']); });
test('native host session launches the selected game before media and rolls it back on failure', async () => { const log = []; const session = createNativeHostSession({platform: 'linux', gameLauncher: component(log, 'game'), mediaPublisher: component(log, 'media'), audioPublisher: component(log, 'audio', true)}); await assert.rejects(() => session.start(), /audio failed/); assert.deepEqual(log, ['game:start', 'media:start', 'audio:start', 'media:stop', 'game:stop']); });
test('native host session stops the game after media and audio', async () => { const log = []; const session = createNativeHostSession({platform: 'linux', gameLauncher: component(log, 'game'), mediaPublisher: component(log, 'media'), audioPublisher: component(log, 'audio')}); await session.start(); await session.stop(); assert.deepEqual(log, ['game:start', 'media:start', 'audio:start', 'audio:stop', 'media:stop', 'game:stop']); });
test('native host session requires active state and configured input', async () => { const session = createNativeHostSession({platform: 'darwin', mediaPublisher: component([], 'media')}); await assert.rejects(() => session.dispatchInput({}), /idle/); await session.start(); await assert.rejects(() => session.dispatchInput({}), /not configured/); await session.stop(); await assert.rejects(() => session.dispatchInput({}), /stopped/); });
