import '../pwa/register.mjs';
import {createWebSocketSignalTransport} from '../transport/transport.mjs';
import {createBrowserWebRtcPublisher} from './browser-publisher.mjs';
import {createBrowserHostRuntime} from './browser-host-runtime.mjs';

export function normalizeBrowserHostConfig(values = {}) { return Object.freeze({endpoint: String(values.endpoint || '').trim(), sessionId: String(values.sessionId || '').trim(), ticket: String(values.ticket || '').trim(), hostId: String(values.hostId || 'browser-host').trim() || 'browser-host', hostName: String(values.hostName || 'Browser Host').trim() || 'Browser Host'}); }

if (typeof document !== 'undefined') {
  const endpoint = document.querySelector('[data-endpoint]'); const sessionId = document.querySelector('[data-session-id]'); const ticket = document.querySelector('[data-ticket]'); const hostId = document.querySelector('[data-host-id]'); const hostName = document.querySelector('[data-host-name]'); const preview = document.querySelector('[data-preview]'); const status = document.querySelector('[data-status]'); const state = document.querySelector('[data-state]'); const log = document.querySelector('[data-log]'); const captureButton = document.querySelector('[data-capture]'); const startButton = document.querySelector('[data-start]'); const stopButton = document.querySelector('[data-stop]');
  let publisher = null; let runtime = null; const messages = [];
  function write(message) { messages.push(`${new Date().toLocaleTimeString()} · ${message}`); log.textContent = messages.slice(-30).join('\n'); }
  function setState(value, message) { state.textContent = value; status.textContent = message; }
  function stop() { runtime?.close(); runtime = null; publisher?.close(); publisher = null; preview.srcObject = null; captureButton.disabled = false; startButton.disabled = true; stopButton.disabled = true; setState('Idle', 'Stopped. Choose a display to begin again.'); write('Host stopped.'); }
  captureButton.addEventListener('click', async () => { try { publisher?.close(); publisher = createBrowserWebRtcPublisher(); const stream = await publisher.capture({audio: false}); preview.srcObject = stream; await preview.play().catch(() => {}); startButton.disabled = false; stopButton.disabled = false; setState('Captured', 'Display selected. Paste a host ticket and start the host.'); write('Display capture granted by the user.'); } catch (error) { setState('Idle', `Capture unavailable: ${error.message}`); write(`Capture failed: ${error.message}`); publisher?.close(); publisher = null; } });
  startButton.addEventListener('click', async () => { try { const config = normalizeBrowserHostConfig({endpoint: endpoint.value, sessionId: sessionId.value, ticket: ticket.value, hostId: hostId.value, hostName: hostName.value}); if (!config.endpoint || !config.sessionId || !config.ticket) throw new Error('Signaling endpoint, session ID, and host ticket are required'); if (!publisher?.stream) throw new Error('Choose a display before starting the host'); const signaling = createWebSocketSignalTransport({endpoint: config.endpoint, join: {sessionId: config.sessionId, role: 'host', ticket: config.ticket}}); runtime = createBrowserHostRuntime({signaling, publisher, sessionId: config.sessionId, hostId: config.hostId, hostName: config.hostName, onInput: event => write(`Input event received: ${event.kind || event.type || 'unknown'}`), onQuality: request => write(`Quality request: ${request.profile || 'custom'}`)}); runtime.on('listening', () => { setState('Listening', 'Waiting for a compatible client offer.'); write('Authenticated host signaling connected.'); }); runtime.on('connected', () => { setState('Connected', 'Remote client negotiated successfully.'); write('WebRTC session connected.'); }); runtime.on('error', error => { setState('Error', error.message); write(`Runtime error: ${error.message}`); }); runtime.on('close', () => write('Signaling connection closed.')); await runtime.start(); startButton.disabled = true; } catch (error) { setState('Error', error.message); write(`Host start failed: ${error.message}`); runtime?.close(); runtime = null; } });
  stopButton.addEventListener('click', stop); window.addEventListener('beforeunload', stop);
}
