import test from 'node:test';
import assert from 'node:assert/strict';
import {createHostConnectionProfile, createHostProfileStore, createPairingRequest, normalizeHostProfile, parseHostEndpoint, selectHostTransport} from './host.mjs';

test('host endpoints reject credentials and insecure remote URLs', () => { assert.throws(() => parseHostEndpoint('https://user:pass@example.test'), /credentials/); assert.throws(() => parseHostEndpoint('http://example.test'), /TLS/); assert.equal(parseHostEndpoint('http://localhost:8787').local, true); });
test('transport selection prefers WebRTC among shared transports', () => { assert.equal(selectHostTransport({clientTransports: ['websocket', 'webrtc'], hostTransports: ['webrtc', 'websocket'], endpoint: 'wss://host.example/session'}), 'webrtc'); assert.throws(() => selectHostTransport({clientTransports: ['webtransport'], hostTransports: ['webtransport'], endpoint: 'http://example.test'}), /TLS/); });
test('pairing requests normalize safe pairing codes and expiry', () => { const request = createPairingRequest({hostId: 'host-1', pairingCode: 'ab-cd23', expiresAt: '2026-08-07T12:00:00Z'}); assert.equal(request.pairingCode, 'ABCD23'); assert.equal(request.type, 'host.pair'); });
test('host connection profile keeps credentials session-scoped', () => { const profile = createHostConnectionProfile({hostId: 'host-1', endpoint: 'wss://host.example/session', hostTransports: ['websocket'], pairingCode: 'ABCD23'}); assert.equal(profile.transport, 'websocket'); assert.equal(profile.credentials, 'session-scoped'); assert.equal(profile.pairing.hostId, 'host-1'); });
test('host profiles normalize transport preferences without storing pairing material', () => { const profile = normalizeHostProfile({hostId: 'host-1', name: 'Living room PC', endpoint: 'wss://host.example/session', hostTransports: ['websocket', 'invalid'], notes: 'Main rig', pairingCode: 'ABCD23'}); assert.deepEqual(profile.hostTransports, ['websocket']); assert.equal('pairingCode' in profile, false); });
test('host profile store saves, exports, imports, and removes profiles', () => { const values = new Map(); const storage = {getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value)}; const store = createHostProfileStore({storage}); store.save({hostId: 'host-1', name: 'Desk PC', endpoint: 'https://host.example'}); assert.equal(store.list().length, 1); const exported = store.export(); const otherValues = new Map(); const other = createHostProfileStore({storage: {getItem: key => otherValues.get(key) ?? null, setItem: (key, value) => otherValues.set(key, value)}}); assert.equal(other.import(exported).length, 1); store.remove('host-1'); assert.equal(store.list().length, 0); });
