import test from 'node:test';
import assert from 'node:assert/strict';
import {clearPendingHostPair, createHostConnectionProfile, createHostProfileStore, createPairingRequest, createPendingHostPair, normalizeHostProfile, parseHostEndpoint, readPendingHostPair, savePendingHostPair, selectHostTransport} from './host.mjs';
import {createHostConfigFromSettings} from './config.mjs';
import './lan-handoff.test.mjs';

test('host endpoints reject credentials and insecure remote URLs', () => { assert.throws(() => parseHostEndpoint('https://user:pass@example.test'), /credentials/); assert.throws(() => parseHostEndpoint('http://example.test'), /TLS/); assert.equal(parseHostEndpoint('http://localhost:8787').local, true); });
test('transport selection prefers WebRTC among shared transports', () => { assert.equal(selectHostTransport({clientTransports: ['websocket', 'webrtc'], hostTransports: ['webrtc', 'websocket'], endpoint: 'wss://host.example/session'}), 'webrtc'); assert.throws(() => selectHostTransport({clientTransports: ['webtransport'], hostTransports: ['webtransport'], endpoint: 'http://example.test'}), /TLS/); });
test('pairing requests normalize safe pairing codes and expiry', () => { const request = createPairingRequest({hostId: 'host-1', pairingCode: 'ab-cd23', expiresAt: '2026-08-07T12:00:00Z'}); assert.equal(request.pairingCode, 'ABCD23'); assert.equal(request.type, 'host.pair'); });
test('host connection profile keeps credentials session-scoped', () => { const profile = createHostConnectionProfile({hostId: 'host-1', endpoint: 'wss://host.example/session', hostTransports: ['websocket'], pairingCode: 'ABCD23'}); assert.equal(profile.transport, 'websocket'); assert.equal(profile.credentials, 'session-scoped'); assert.equal(profile.pairing.hostId, 'host-1'); });
test('host profiles normalize transport preferences without storing pairing material', () => { const profile = normalizeHostProfile({hostId: 'host-1', name: 'Living room PC', endpoint: 'wss://host.example/session', hostTransports: ['websocket', 'invalid'], notes: 'Main rig', pairingCode: 'ABCD23'}); assert.deepEqual(profile.hostTransports, ['websocket']); assert.equal('pairingCode' in profile, false); });
test('host profile store saves, exports, imports, and removes profiles', () => { const values = new Map(); const storage = {getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value)}; const store = createHostProfileStore({storage}); store.save({hostId: 'host-1', name: 'Desk PC', endpoint: 'https://host.example'}); assert.equal(store.list().length, 1); const exported = store.export(); const otherValues = new Map(); const other = createHostProfileStore({storage: {getItem: key => otherValues.get(key) ?? null, setItem: (key, value) => otherValues.set(key, value)}}); assert.equal(other.import(exported).length, 1); store.remove('host-1'); assert.equal(store.list().length, 0); });
test('host settings convert to a portable secret-free agent configuration', () => { const config = createHostConfigFromSettings({platform: 'win32', host: {hostId: 'host-1', name: 'Desk PC'}, settings: {'host.sessionPort': 99999, 'host.nativePackage': '@spartan/native-windows', 'controllers.virtualGamepadBackend': 'Windows external driver', 'controllers.virtualGamepadPackage': '@spartan/windows-driver', 'controllers.virtualGamepadDevice': 'xinput-0', 'controllers.virtualGamepadDevices': 'xinput-0, xinput-1', 'host.allowInputInjection': true, 'host.enableNativeMedia': true, 'host.enableNativeAudio': true, 'host.audioBackend': 'WASAPI'}}); assert.equal(config.hostId, 'host-1'); assert.equal(config.port, 65535); assert.equal(config.virtualGamepadPackage, '@spartan/windows-driver'); assert.deepEqual(config.virtualGamepadDevices, ['xinput-0', 'xinput-1']); assert.equal(config.audioBackend, 'WASAPI'); assert.equal('pairingCode' in config, false); });
test('pending host handoff validates endpoint, pairing expiry, and session-only storage', () => { const values = new Map(); const storage = {getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key)}; const pending = savePendingHostPair(storage, {hostId: 'host-1', name: 'Desk PC', endpoint: 'ws://localhost:8787/session', pairingCode: 'ABCD23', expiresAt: new Date(Date.now() + 60_000).toISOString()}); assert.equal(pending.endpoint, 'ws://localhost:8787/session'); assert.equal(readPendingHostPair(storage).pairingCode, 'ABCD23'); assert.equal(JSON.stringify(pending).includes('ticket'), false); clearPendingHostPair(storage); assert.equal(readPendingHostPair(storage), null); assert.throws(() => createPendingHostPair({hostId: 'host-1', name: 'Desk PC', endpoint: 'http://example.test/session', pairingCode: 'ABCD23'}), /TLS|ws or wss/); });
test('expired pending host handoffs fail closed', () => { const pending = createPendingHostPair({hostId: 'host-1', name: 'Desk PC', endpoint: 'ws://localhost:8787/session', pairingCode: 'ABCD23', expiresAt: new Date(Date.now() - 1).toISOString()}); const storage = {getItem: () => JSON.stringify(pending)}; assert.equal(readPendingHostPair(storage), null); });
