import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatalogAdapterRegistry, resolveLaunchPlan} from './adapters.mjs';

const cloud = {id: 'cloud', name: 'Cloud', backendType: 'provider', integrationModes: ['browser-first', 'official-launch'], url: 'https://example.test', requirements: ['account'], capabilities: ['gamepad']};
const emulator = {id: 'emu', name: 'Emu', backendType: 'emulator', mode: 'browser-or-native', integrationModes: ['browser-or-native'], capabilities: ['gamepad']};

test('provider launch plans prefer an official browser handoff', () => { const plan = resolveLaunchPlan(cloud); assert.equal(plan.action, 'open-url'); assert.equal(plan.url, cloud.url); assert.deepEqual(plan.requirements, ['account']); });
test('emulator plans expose runtime choice instead of pretending to launch', () => { const plan = resolveLaunchPlan(emulator); assert.equal(plan.action, 'choose-runtime'); assert.equal(plan.external, false); });
test('unsupported modes return a structured support error', () => { const plan = resolveLaunchPlan({...cloud, integrationModes: ['private-api']}); assert.equal(plan.status, 'unsupported'); assert.equal(plan.action, 'show-support-error'); });
test('catalog adapter registry resolves immutable descriptors', () => { const registry = createCatalogAdapterRegistry([cloud, emulator]); assert.equal(registry.list().length, 2); assert.equal(registry.get('cloud').resolve().backendId, 'cloud'); assert.equal(Object.isFrozen(registry.get('cloud')), true); });
test('provider launch plans honor saved official launch preferences', () => { const plan = resolveLaunchPlan({...cloud, integrationModes: ['browser-first', 'official-launch']}, {providerProfile: {launchMode: 'official'}}); assert.equal(plan.mode, 'official-launch'); assert.equal(plan.integration.controllerProfile, 'Auto-detect'); });
test('launch plans expose capability readiness and a concrete next action', () => { const plan = resolveLaunchPlan(cloud, {providerProfile: {report: {input: {gamepad: false}, transports: {webrtc: true}}}}); assert.equal(plan.readiness.status, 'browser-capability-missing'); assert.equal(plan.readiness.nextAction, 'run-diagnostics'); assert.deepEqual(plan.readiness.missingCapabilities, ['gamepad']); assert.equal(plan.readiness.issues[0].key, 'gamepad'); });
test('native emulator plans explain adapter readiness without claiming a launch', () => { const plan = resolveLaunchPlan({id: 'pcsx2', name: 'PCSX2', backendType: 'emulator', mode: 'native', integrationModes: ['native'], systems: ['playstation-2'], license: 'GPL-3.0-or-later'}, {providerProfile: {report: {graphics: {webgpuAdapter: true}, input: {gamepad: true}}}}); assert.equal(plan.action, 'configure-native-adapter'); assert.equal(plan.readiness.status, 'native-adapter-required'); assert.equal(plan.readiness.nextAction, 'choose-runtime'); assert.equal(plan.readiness.issues[0].key, 'firmware'); });
test('catalog adapter registry can read a live capability report', () => { let report = {input: {gamepad: false}, transports: {webrtc: true}}; const registry = createCatalogAdapterRegistry([{...cloud, requirements: ['provider-account']}], {report: () => report}); assert.equal(registry.get('cloud').resolve().readiness.status, 'browser-capability-missing'); report = {input: {gamepad: true}, transports: {webrtc: true}}; assert.equal(registry.get('cloud').resolve().readiness.status, 'configuration-required'); });
