import '../pwa/register.mjs';
import {createSettingsStore} from '../settings/profile.mjs';
import {createAdapterManagerModel, detectAdapterPlatform, readAdapterManifestBundle} from './manager.mjs';
import {createAdapterReleaseInstallRequest} from './install.mjs';

const state = {cores: [], records: [], releaseFeed: null, platform: detectAdapterPlatform(), allowUnsigned: false, query: '', model: null};
const runtimeList = document.querySelector('[data-runtime-list]'); const manifestList = document.querySelector('[data-manifest-list]'); const notice = document.querySelector('[data-notice]'); let timer;
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[character])); }
function toast(message) { notice.textContent = message; notice.classList.add('visible'); clearTimeout(timer); timer = setTimeout(() => notice.classList.remove('visible'), 2800); }
function statusLabel(row) { return row.status === 'browser-runtime' ? 'Browser-WASM eligible' : row.status === 'ready' ? `Signed · ${row.adapter.version}` : row.status === 'ready-unsigned' ? `Unsigned dev · ${row.adapter.version}` : row.status === 'blocked' ? 'Blocked by trust policy' : 'Adapter not installed'; }
function releaseLabel(row) { const release = row.release; if (!release) return null; if (release.status === 'install-available') return `Release v${release.to} available`; if (release.status === 'update-available') return `Update v${release.from} → v${release.to}`; if (release.status === 'up-to-date') return `Up to date · v${release.version}`; return null; }
function releaseAction(row) { return row.release?.status === 'install-available' ? 'Install' : row.release?.status === 'update-available' ? 'Update' : null; }
function renderInstallHandoff(row, button) {
  button.disabled = true;
  try {
    const request = createAdapterReleaseInstallRequest({plan: row.release, platform: state.platform, consent: true});
    const blob = new Blob([JSON.stringify(request, null, 2)], {type: 'application/json'});
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `spartan-adapter-${request.id}-${request.to}.install.json`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0);
    toast(`${request.id}: consented install handoff downloaded. Apply it with the host updater.`);
  } catch (error) { toast(error.message); }
  button.disabled = false;
}
function render() { const query = state.query.toLowerCase(); const rows = state.model?.rows.filter(row => `${row.name} ${row.id} ${(row.systems || []).join(' ')}`.toLowerCase().includes(query)) || []; document.querySelector('[data-core-count]').textContent = state.cores.length; document.querySelector('[data-manifest-count]').textContent = state.model?.manifests.length || 0; document.querySelector('[data-browser-count]').textContent = state.model?.rows.filter(row => row.browserReady).length || 0; document.querySelector('[data-status]').textContent = `${state.platform} · ${rows.length} shown`; runtimeList.innerHTML = rows.length ? rows.map(row => { const action = releaseAction(row); const label = releaseLabel(row); return `<article class="runtime-row"><div><h3>${escapeHtml(row.name)}</h3><p>${escapeHtml(row.id)} · ${escapeHtml(row.mode)} · ${escapeHtml(row.license || 'License not declared')}</p><div class="tags">${row.systems.map(system => `<span class="tag">${escapeHtml(system)}</span>`).join('')}${label ? `<span class="tag release">${escapeHtml(label)}</span>` : ''}</div></div><span class="status ${escapeHtml(row.status)}">${escapeHtml(statusLabel(row))}</span><small>${escapeHtml(row.reason || 'Ready for the selected runtime.')}</small>${action ? `<button class="secondary" data-install="${escapeHtml(row.id)}" type="button">${escapeHtml(action)}</button>` : ''}</article>`; }).join('') : '<p class="empty">No cores match this search.</p>'; runtimeList.querySelectorAll('[data-install]').forEach(button => button.addEventListener('click', () => { const row = state.model?.rows.find(item => item.id === button.dataset.install); if (!row) return; if (!globalThis.confirm(`Create a signed ${releaseAction(row)} handoff for ${row.name}? The host updater verifies and applies it.`)) return; renderInstallHandoff(row, button); })); const manifests = state.model?.manifests || []; manifestList.innerHTML = manifests.length ? manifests.map(record => `<article class="manifest-row"><div><strong>${escapeHtml(record.id)}</strong><small>${escapeHtml(record.kind)} · v${escapeHtml(record.version)} · ${escapeHtml(record.platforms.join(', '))}</small></div><span class="status ${record.trust === 'signed' ? 'ready' : 'blocked'}">${escapeHtml(record.trust)}</span><small>${escapeHtml(record.signature?.signer || 'No release signer')}</small></article>`).join('') : '<p class="empty">No adapter manifests have been injected or imported.</p>'; }
async function load() { try { const manifest = await fetch('../../../emulators/catalog.json').then(response => response.json()); state.cores = manifest.projects; const injected = globalThis.__SPARTAN_ADAPTER_MANIFESTS__; if (injected) state.records = [...readAdapterManifestBundle(injected)]; const releaseFeed = globalThis.__SPARTAN_RELEASE_FEED__; state.releaseFeed = releaseFeed || null; state.allowUnsigned = createSettingsStore().read()['advanced.allowUnsignedAdapters'] === true; document.querySelector('[data-platform]').value = state.platform; rebuild(); } catch (error) { runtimeList.innerHTML = `<p class="empty">${escapeHtml(error.message)}</p>`; } }
function rebuild() { state.model = createAdapterManagerModel({cores: state.cores, records: state.records, feed: state.releaseFeed, platform: state.platform, allowUnsigned: state.allowUnsigned}); render(); }
document.querySelector('[data-search]').addEventListener('input', event => { state.query = event.target.value; render(); });
document.querySelector('[data-platform]').addEventListener('change', event => { state.platform = event.target.value; rebuild(); });
document.querySelector('[data-unsigned]').addEventListener('change', event => { state.allowUnsigned = event.target.checked; rebuild(); });
document.querySelector('[data-import]').addEventListener('click', () => document.querySelector('[data-file]').click());
document.querySelector('[data-file]').addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; try { state.records = [...readAdapterManifestBundle(await file.text())]; rebuild(); toast(`${state.records.length} verified manifest${state.records.length === 1 ? '' : 's'} loaded.`); } catch (error) { toast(`Manifest import rejected: ${error.message}`); } event.target.value = ''; });
load();
