import test from 'node:test';
import assert from 'node:assert/strict';
import {createAdapterManagerModel, detectAdapterPlatform, readAdapterManifestBundle, readReleaseFeed} from './manager.mjs';

const signed = {id: 'pcsx2', version: '1.0.0', kind: 'emulator', status: 'installed', trust: 'signed', platforms: ['linux'], capabilities: ['video'], license: 'GPL-3.0-or-later', integrity: 'sha256-pcsx2', signature: {algorithm: 'ECDSA-P256-SHA256', signer: 'release', value: 'sig'}};
test('adapter manager distinguishes browser-capable cores from native adapter readiness', () => { const model = createAdapterManagerModel({platform: 'linux', records: [signed], cores: [{id: 'libretro', name: 'Libretro', mode: 'browser-or-native'}, {id: 'pcsx2', name: 'PCSX2', mode: 'native'}, {id: 'dolphin', name: 'Dolphin', mode: 'native'}]}); assert.equal(model.rows[0].status, 'browser-runtime'); assert.equal(model.rows[1].status, 'ready'); assert.equal(model.rows[2].status, 'unavailable'); });
test('adapter manager normalizes manifest bundles and detects desktop platforms', () => { assert.equal(readAdapterManifestBundle({records: [signed]})[0].id, 'pcsx2'); assert.equal(detectAdapterPlatform('Win32'), 'win32'); assert.equal(detectAdapterPlatform('MacIntel'), 'darwin'); assert.equal(detectAdapterPlatform('Linux x86_64'), 'linux'); assert.equal(detectAdapterPlatform('Android'), 'browser'); });
test('adapter manager rejects malformed manifest bundles', () => { assert.throws(() => readAdapterManifestBundle({records: [{id: 'broken'}]}), /non-empty/); assert.throws(() => readAdapterManifestBundle({records: 'broken'}), /contain/); });
test('adapter manager merges release feed records ahead of injected manifests', () => { const rawFeed = {schemaVersion: 1, records: [{...signed, id: 'dolphin', version: '2.0.0', integrity: 'sha256-feed'}]}; assert.equal(readReleaseFeed(rawFeed)[0].id, 'dolphin'); const model = createAdapterManagerModel({platform: 'linux', records: [{...signed, id: 'dolphin', version: '1.0.0'}], feed: rawFeed, cores: [{id: 'dolphin', name: 'Dolphin', mode: 'native'}]}); assert.equal(model.registry.get('dolphin').version, '2.0.0'); assert.throws(() => readReleaseFeed({schemaVersion: 2, records: []}), /schemaVersion/); });
test('adapter manager exposes install and update plans from the release feed', () => { const feed = {schemaVersion: 1, records: [{...signed, id: 'pcsx2', version: '1.1.0', integrity: 'sha256-feed', artifact: {url: 'https://downloads.example.test/pcsx2.tar.zst', sizeBytes: 1024, integrity: 'sha256-feed'}}, {...signed, id: 'dolphin', version: '2.0.0', integrity: 'sha256-dolphin'}]}; const fresh = createAdapterManagerModel({platform: 'linux', feed, cores: [{id: 'pcsx2', name: 'PCSX2', mode: 'native'}, {id: 'dolphin', name: 'Dolphin', mode: 'native'}]}); assert.equal(fresh.rows[0].release.status, 'install-available'); assert.equal(fresh.rows[0].release.to, '1.1.0'); const current = createAdapterManagerModel({platform: 'linux', records: [{...signed, id: 'pcsx2', version: '1.0.0'}], feed, cores: [{id: 'pcsx2', name: 'PCSX2', mode: 'native'}]}); assert.equal(current.rows[0].release.status, 'update-available'); assert.equal(current.rows[0].release.from, '1.0.0'); assert.equal(current.rows[0].release.to, '1.1.0'); const upToDate = createAdapterManagerModel({platform: 'linux', records: [{...signed, id: 'pcsx2', version: '1.1.0'}], feed, cores: [{id: 'pcsx2', name: 'PCSX2', mode: 'native'}]}); assert.equal(upToDate.rows[0].release.status, 'up-to-date'); const none = createAdapterManagerModel({platform: 'linux', records: [], feed: {schemaVersion: 1, records: [{...signed, id: 'unrelated', version: '9.9.9', integrity: 'sha256-x'}]}, cores: [{id: 'pcsx2', name: 'PCSX2', mode: 'native'}]}); assert.equal(none.rows[0].release, null); });
