import assert from 'node:assert/strict';
import test from 'node:test';
import {createAdapterManifestRegistry, evaluateAdapterManifest, normalizeAdapterManifest, verifyAdapterSignature} from './manifest-registry.mjs';

const signed = {id: 'dolphin-native', version: '1.0.0', kind: 'emulator', status: 'installed', trust: 'signed', platforms: ['win32', 'linux'], capabilities: ['video', 'audio'], license: 'GPL-2.0-or-later', integrity: 'sha256-abc123', signature: {algorithm: 'ECDSA-P256-SHA256', signer: 'spartan-release', value: 'c2lnbmF0dXJl'}};

test('adapter manifests require integrity, licensing, platform, and trust metadata', () => { const record = normalizeAdapterManifest(signed); assert.equal(record.id, 'dolphin-native'); assert.equal(record.signature.signer, 'spartan-release'); assert.throws(() => normalizeAdapterManifest({...signed, integrity: 'md5-nope'}), /sha256/); assert.throws(() => normalizeAdapterManifest({...signed, license: ''}), /license/); });
test('adapter registry resolves signed, unsigned, blocked, and platform-mismatched adapters', () => { const registry = createAdapterManifestRegistry({platform: 'linux', records: [signed, {...signed, id: 'dev-core', trust: 'unsigned'}, {...signed, id: 'blocked-core', status: 'blocked'}]}); assert.equal(registry.resolve('dolphin-native', {kind: 'emulator'}).status, 'ready'); assert.equal(registry.resolve('dev-core').status, 'blocked'); assert.equal(registry.resolve('dev-core', {allowUnsigned: true}).status, 'ready-unsigned'); assert.equal(registry.resolve('blocked-core').status, 'blocked'); assert.equal(registry.resolve('missing').status, 'unavailable'); assert.equal(evaluateAdapterManifest(signed, {platform: 'darwin'}).status, 'unavailable'); });
test('adapter registry rejects duplicate manifests and unsupported kinds', () => { assert.throws(() => createAdapterManifestRegistry({records: [signed, signed]}), /duplicate/); assert.throws(() => normalizeAdapterManifest({...signed, kind: 'script'}), /unsupported adapter kind/); });
test('WebCrypto adapter signature verification uses the declared algorithm and public key', async () => { const calls = []; const subtle = {async importKey(...args) { calls.push(['importKey', ...args]); return 'public-key'; }, async verify(...args) { calls.push(['verify', ...args]); return true; }}; const valid = await verifyAdapterSignature({data: 'manifest-payload', signature: signed.signature, publicKeyJwk: {kty: 'EC', crv: 'P-256'}, subtle}); assert.equal(valid, true); assert.equal(calls[0][0], 'importKey'); assert.equal(calls[1][0], 'verify'); assert.deepEqual(calls[1][1], {name: 'ECDSA', hash: 'SHA-256'}); });
