import assert from 'node:assert/strict';
import test from 'node:test';
import {createAdapterManifestRegistry, createAdapterUpdatePlan, evaluateAdapterManifest, normalizeAdapterManifest, verifyAdapterSignature} from './manifest-registry.mjs';
import {createAdapterInstallRequest} from './install.mjs';

const signed = {id: 'dolphin-native', version: '1.0.0', kind: 'emulator', status: 'installed', trust: 'signed', platforms: ['win32', 'linux'], capabilities: ['video', 'audio'], license: 'GPL-2.0-or-later', integrity: 'sha256-abc123', signature: {algorithm: 'ECDSA-P256-SHA256', signer: 'spartan-release', value: 'c2lnbmF0dXJl'}};

test('adapter manifests require integrity, licensing, platform, and trust metadata', () => { const record = normalizeAdapterManifest(signed); assert.equal(record.id, 'dolphin-native'); assert.equal(record.signature.signer, 'spartan-release'); assert.throws(() => normalizeAdapterManifest({...signed, integrity: 'md5-nope'}), /sha256/); assert.throws(() => normalizeAdapterManifest({...signed, license: ''}), /license/); });
test('adapter registry resolves signed, unsigned, blocked, and platform-mismatched adapters', () => { const registry = createAdapterManifestRegistry({platform: 'linux', records: [signed, {...signed, id: 'dev-core', trust: 'unsigned'}, {...signed, id: 'blocked-core', status: 'blocked'}]}); assert.equal(registry.resolve('dolphin-native', {kind: 'emulator'}).status, 'ready'); assert.equal(registry.resolve('dev-core').status, 'blocked'); assert.equal(registry.resolve('dev-core', {allowUnsigned: true}).status, 'ready-unsigned'); assert.equal(registry.resolve('blocked-core').status, 'blocked'); assert.equal(registry.resolve('missing').status, 'unavailable'); assert.equal(evaluateAdapterManifest(signed, {platform: 'darwin'}).status, 'unavailable'); });
test('adapter registry rejects duplicate manifests and unsupported kinds', () => { assert.throws(() => createAdapterManifestRegistry({records: [signed, signed]}), /duplicate/); assert.throws(() => normalizeAdapterManifest({...signed, kind: 'script'}), /unsupported adapter kind/); });
test('WebCrypto adapter signature verification uses the declared algorithm and public key', async () => { const calls = []; const subtle = {async importKey(...args) { calls.push(['importKey', ...args]); return 'public-key'; }, async verify(...args) { calls.push(['verify', ...args]); return true; }}; const valid = await verifyAdapterSignature({data: 'manifest-payload', signature: signed.signature, publicKeyJwk: {kty: 'EC', crv: 'P-256'}, subtle}); assert.equal(valid, true); assert.equal(calls[0][0], 'importKey'); assert.equal(calls[1][0], 'verify'); assert.deepEqual(calls[1][1], {name: 'ECDSA', hash: 'SHA-256'}); });
test('adapter update plans select the highest compatible signed release', () => { const plan = createAdapterUpdatePlan({current: {...signed, version: '1.0.0'}, platform: 'linux', kind: 'emulator', candidates: [{...signed, version: '1.1.0', integrity: 'sha256-newer'}, {...signed, version: '2.0.0', trust: 'unsigned', integrity: 'sha256-dev'}, {...signed, version: '1.2.0', status: 'blocked', integrity: 'sha256-blocked'}]}); assert.equal(plan.status, 'update-available'); assert.equal(plan.to, '1.1.0'); assert.equal(plan.readiness.status, 'ready'); });
test('adapter update plans fail closed when only unsigned newer releases exist', () => { const plan = createAdapterUpdatePlan({current: signed, platform: 'linux', candidates: [{...signed, version: '2.0.0', trust: 'unsigned', integrity: 'sha256-dev'}]}); assert.equal(plan.status, 'up-to-date'); assert.match(plan.reason, /trusted/); });
test('adapter install requests require consent and a verified artifact descriptor', () => { const plan = createAdapterUpdatePlan({current: signed, platform: 'linux', candidates: [{...signed, version: '1.1.0', integrity: 'sha256-newer', artifact: {url: 'https://downloads.example.test/dolphin.tar.zst', sizeBytes: 1024, integrity: 'sha256-newer'}}]}); assert.throws(() => createAdapterInstallRequest({updatePlan: plan, platform: 'linux'}), /consent/); const request = createAdapterInstallRequest({updatePlan: plan, platform: 'linux', consent: true}); assert.equal(request.artifact.url, 'https://downloads.example.test/dolphin.tar.zst'); assert.equal(request.installScope, 'user'); assert.equal(Object.hasOwn(request, 'credential'), false); });
test('adapter manifests reject insecure or mismatched artifact metadata', () => { assert.throws(() => normalizeAdapterManifest({...signed, artifact: {url: 'http://downloads.example.test/a', sizeBytes: 1, integrity: signed.integrity}}), /https/); assert.throws(() => normalizeAdapterManifest({...signed, artifact: {url: 'https://downloads.example.test/a', sizeBytes: 1, integrity: 'sha256-other'}}), /match/); });
