import test from 'node:test';
import assert from 'node:assert/strict';
import {createEmulationLaunchPlan, createEmulationLibraryIndex, createEmulationLibraryStore, createUserFileRecord, formatFileSize, resolveEmulationPreferences} from './emulation.mjs';
import './browser-runtime.test.mjs';
import './browser-adapters.test.mjs';

const core = {id: 'dolphin', mode: 'native', systems: ['gamecube', 'wii'], license: 'GPL-2.0-or-later'};
test('user file records preserve selection metadata without file contents', () => { const record = createUserFileRecord({name: 'game.iso', size: 1024, lastModified: 10}); assert.equal(record.extension, 'iso'); assert.equal(record.userSelected, true); assert.equal(record.content, undefined); });
test('library index deduplicates selected files', () => { const file = {name: 'game.rom', size: 100}; assert.equal(createEmulationLibraryIndex([file, file]).length, 1); });
test('emulation library persists metadata without file contents or launch authority', () => { const values = new Map(); const storage = {getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value)}; const store = createEmulationLibraryStore({storage}); const record = createUserFileRecord({name: 'game.iso', size: 200, lastModified: 12}, {kind: 'game'}); store.add([record]); assert.equal(store.list()[0].name, 'game.iso'); assert.equal(store.list()[0].userSelected, false); assert.equal(store.list()[0].content, undefined); const restored = createEmulationLibraryStore({storage}); assert.equal(restored.list().length, 1); assert.throws(() => createEmulationLaunchPlan({core, gameFile: restored.list()[0]}), /selected/); });
test('emulation library removes remembered metadata safely', () => { const values = new Map(); const storage = {getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value)}; const store = createEmulationLibraryStore({storage}); const record = createUserFileRecord({name: 'game.rom', size: 20}, {kind: 'game'}); store.add([record]); assert.equal(store.remove(record.id).length, 0); });
test('launch plans require legal user-selected game and firmware files', () => { const plan = createEmulationLaunchPlan({core, gameFile: {name: 'game.iso', size: 10}, firmwareFiles: [{name: 'bios.bin', size: 2}]}); assert.equal(plan.status, 'ready'); assert.deepEqual(plan.files.map(file => file.kind), ['game', 'firmware']); assert.equal(plan.policy.shipRoms, false); });
test('launch plans fail closed for missing license or unselected content', () => { assert.throws(() => createEmulationLaunchPlan({core: {...core, license: ''}, gameFile: {name: 'game.iso'}}), /license/); assert.throws(() => createEmulationLaunchPlan({core, gameFile: {name: 'game.iso', userSelected: false}}), /selected/); });
test('launch plans require firmware when the selected runtime declares it', () => { const pcsx2 = {id: 'pcsx2', mode: 'native', systems: ['playstation-2'], license: 'GPL-3.0-or-later'}; assert.throws(() => createEmulationLaunchPlan({core: pcsx2, gameFile: {name: 'game.iso'}}), /firmware/); });
test('file sizes are human-readable', () => { assert.equal(formatFileSize(1024 ** 2), '1.0 MB'); });
test('emulation preferences translate settings into integration choices', () => { assert.deepEqual(resolveEmulationPreferences({'emulation.frontend': 'Spartan runtime', 'emulation.renderer': 'Metal'}), {preference: 'spartan-runtime', renderer: 'Metal'}); assert.deepEqual(resolveEmulationPreferences({'emulation.frontend': 'unknown', 'emulation.renderer': ''}), {preference: 'automatic', renderer: 'Automatic'}); });
