import '../pwa/register.mjs';
import {createEmulationLaunchPlan, createEmulationLibraryStore, createUserFileRecord, formatFileSize, resolveEmulationPreferences} from './emulation.mjs';
import {createEmulatorIntegration, emulatorTroubleshooting} from './integration.mjs';
import {clearLaunchIntent, readLaunchIntent} from '../launch/intent.mjs';
import {collectCapabilities} from '../diagnostics/capabilities.mjs';
import {createSettingsStore} from '../settings/profile.mjs';
import {createRuntimeProfileStore} from './runtime-profiles.mjs';

const runtimeStore = createRuntimeProfileStore();
const state = {cores: [], gameFiles: [], firmwareFiles: [], rememberedFiles: [], runtimeProfiles: runtimeStore.list(), report: null, capabilitiesReady: false, preferences: resolveEmulationPreferences()};
const library = createEmulationLibraryStore();
const coreList = document.querySelector('[data-core-list]');
const fileList = document.querySelector('[data-file-list]');
const notice = document.querySelector('[data-notice]');
const runtimePanel = document.createElement('section');
runtimePanel.className = 'runtime-manager panel';
runtimePanel.innerHTML = '<div class="panel-head"><div><p class="eyebrow">TRUSTED RUNTIME PROFILES</p><h2>Manage local runtimes</h2></div><span>Metadata only</span></div><p class="runtime-help">Profiles describe user-owned native adapters, Libretro hosts, or browser runtimes. Spartan Gaming never launches a path from this page; a signed host adapter performs any native handoff.</p><form class="runtime-form" data-runtime-form><label>ID<input name="id" required pattern="[a-z0-9][a-z0-9._-]{1,63}" placeholder="dolphin-linux"></label><label>Name<input name="name" required maxlength="160" placeholder="Dolphin Linux"></label><label>Kind<select name="kind"><option value="native-emulator">Native emulator</option><option value="native-adapter">Native adapter</option><option value="libretro-core">Libretro core host</option><option value="browser-wasm">Browser WASM</option></select></label><label>Platform<select name="platform"><option value="any">Any</option><option value="linux">Linux</option><option value="darwin">macOS</option><option value="win32">Windows</option><option value="browser">Browser</option></select></label><label>Version<input name="version" required placeholder="5.0"></label><label>Core IDs<input name="coreIds" required placeholder="dolphin, libretro"></label><label class="wide">Executable or adapter path<input name="executablePath" placeholder="/opt/dolphin/dolphin-emu"></label><label>Trust<select name="trust"><option value="user-approved">User approved</option><option value="signed">Signed</option><option value="unverified">Unverified (not selectable)</option></select></label><label>Notes<input name="notes" maxlength="500" placeholder="Optional local notes"></label><button class="file-button" type="submit">＋ Save runtime profile</button></form><div data-runtime-list class="runtime-list"><p class="empty">No custom runtime profiles.</p></div>';
coreList.closest('.panel').before(runtimePanel);
const runtimeList = runtimePanel.querySelector('[data-runtime-list]');
const planPanel = document.createElement('section');
planPanel.className = 'panel launch-plan';
planPanel.hidden = true;
coreList.closest('.panel').before(planPanel);
function toast(message) { notice.textContent = message; notice.classList.add('visible'); setTimeout(() => notice.classList.remove('visible'), 2500); }
function allFiles() { return [...state.gameFiles, ...state.firmwareFiles]; }
function renderFiles() { const files = allFiles(); document.querySelector('[data-file-count]').textContent = `${files.length} file${files.length === 1 ? '' : 's'}`; fileList.innerHTML = files.length ? files.map(file => `<div class="file-entry"><strong>${file.name}</strong><small>${file.kind} · ${formatFileSize(file.size)} · ready this session</small></div>`).join('') : '<p class="empty">No files selected. Your files stay local to this browser.</p>'; }
function renderRememberedFiles() { const container = document.querySelector('[data-library-list]'); container.innerHTML = state.rememberedFiles.length ? state.rememberedFiles.map(file => `<div class="file-entry remembered"><div><strong>${file.name}</strong><small>${file.kind} · ${formatFileSize(file.size)} · re-select to use</small></div><button class="text-button" data-remove-library="${file.id}" type="button" aria-label="Forget ${file.name}">Forget</button></div>`).join('') : '<p class="empty">No remembered files yet.</p>'; }
function escapeHtml(value) { return String(value).replace(/[&<>\'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character])); }
function renderRuntimeProfiles() { runtimeList.innerHTML = state.runtimeProfiles.length ? state.runtimeProfiles.map(profile => `<div class="runtime-entry"><div><strong>${escapeHtml(profile.name)}</strong><small>${escapeHtml(profile.kind)} · ${escapeHtml(profile.platform)} · ${escapeHtml(profile.version)} · ${escapeHtml(profile.trust)}</small></div><button class="text-button" data-remove-runtime="${escapeHtml(profile.id)}" type="button" aria-label="Remove ${escapeHtml(profile.name)}">Remove</button></div>`).join('') : '<p class="empty">No custom runtime profiles. Browser WASM is available when the browser passes capability checks.</p>'; }
function renderLaunchPlan(plan, core) { const firmware = plan.integration.content.firmwareFiles ? 'Required' : 'Not required'; planPanel.hidden = false; planPanel.innerHTML = `<div class="panel-head"><div><p class="eyebrow">LAUNCH PLAN</p><h2>${core.name}</h2></div><span class="tag">${plan.status}</span></div><div class="plan-grid"><div><small>Runtime</small><strong>${plan.integration.runtime}</strong></div><div><small>Renderer</small><strong>${plan.integration.renderer}</strong></div><div><small>Systems</small><strong>${plan.systems.join(', ') || 'General'}</strong></div><div><small>Firmware</small><strong>${firmware}</strong></div></div><p class="plan-note">${plan.integration.notes[0] || 'Only user-selected files are mounted. Content remains local to this browser.'}</p><div class="plan-files">${plan.files.map(file => `<span class="tag">${file.kind}: ${file.name}</span>`).join('')}</div>`; planPanel.scrollIntoView({behavior: 'smooth', block: 'nearest'}); }
function renderCores() { document.querySelector('[data-core-count]').textContent = `${state.cores.length} runtimes · ${state.capabilitiesReady ? 'browser probed' : 'checking browser'}`; coreList.innerHTML = state.cores.map(core => { const integration = createEmulatorIntegration(core, {...state.preferences, runtimeProfiles: state.runtimeProfiles, platform: state.report?.browser?.platform || 'browser', report: state.report || {graphics: {webgpuAdapter: false, webgl: false}}}); const issues = emulatorTroubleshooting(integration); const readiness = integration.runtime === 'browser-wasm' ? (state.capabilitiesReady ? (integration.browserReady ? 'Browser ready' : 'Native fallback') : 'Checking…') : integration.runtimeReadiness?.status === 'ready' ? 'Profile ready' : 'Profile needed'; const profile = integration.runtimeProfile ? ` · ${integration.runtimeProfile.name}` : ''; return `<article class="core-card"><h3>${escapeHtml(core.name)}</h3><p>${escapeHtml(integration.runtime)} · ${escapeHtml(integration.renderer)}${escapeHtml(profile)}</p><div class="core-tags"><span class="tag">${escapeHtml(readiness)}</span>${core.systems.map(system => `<span class="tag">${escapeHtml(system)}</span>`).join('')}${integration.features.slice(0, 2).map(feature => `<span class="tag">${escapeHtml(feature)}</span>`).join('')}</div><small class="core-note">${escapeHtml(issues[0]?.message || integration.notes[0] || 'User-selected files only')}</small><button class="launch" data-launch="${escapeHtml(core.id)}" ${state.gameFiles.length ? '' : 'disabled'}>Prepare launch plan</button></article>`; }).join(''); coreList.querySelectorAll('[data-launch]').forEach(button => button.addEventListener('click', () => { const core = state.cores.find(item => item.id === button.dataset.launch); try { const plan = createEmulationLaunchPlan({core, gameFile: state.gameFiles[0], firmwareFiles: state.firmwareFiles, ...state.preferences, runtimeProfiles: state.runtimeProfiles, platform: state.report?.browser?.platform || 'browser', report: state.report || {graphics: {webgpuAdapter: false, webgl: false}}}); renderLaunchPlan(plan, core); toast(`${core.name}: ${plan.integration.runtime} · ${plan.integration.renderer} plan ready.`); } catch (error) { toast(error.message); } })); }
async function loadCores() { try { state.preferences = resolveEmulationPreferences(createSettingsStore().read()); const manifest = await fetch('../../../emulators/catalog.json').then(response => response.json()); state.cores = manifest.projects; renderCores(); collectCapabilities().then(report => { state.report = report; state.capabilitiesReady = true; renderCores(); }).catch(() => { state.capabilitiesReady = true; renderCores(); }); const intent = readLaunchIntent(sessionStorage); const core = state.cores.find(item => item.id === intent?.backendId); if (intent?.backendType === 'emulator' && core) { toast(`${core.name}: ${intent.mode} runtime selected. Add your game files to continue.`); clearLaunchIntent(sessionStorage); } } catch { coreList.innerHTML = '<p class="empty">The emulator catalog could not be loaded.</p>'; } }
function addFiles(files, kind) { const records = [...files].map(file => createUserFileRecord(file, {kind})); if (kind === 'game') state.gameFiles.push(...records); else state.firmwareFiles.push(...records); state.rememberedFiles = library.add(records); renderFiles(); renderRememberedFiles(); renderCores(); toast(`${records.length} user-selected ${kind} file${records.length === 1 ? '' : 's'} added and remembered as metadata.`); }
document.querySelector('[data-runtime-form]').addEventListener('submit', event => { event.preventDefault(); const form = event.currentTarget; try { runtimeStore.save({id: form.elements.id.value, name: form.elements.name.value, kind: form.elements.kind.value, platform: form.elements.platform.value, version: form.elements.version.value, coreIds: form.elements.coreIds.value.split(',').map(value => value.trim()).filter(Boolean), executablePath: form.elements.executablePath.value, trust: form.elements.trust.value, notes: form.elements.notes.value}); state.runtimeProfiles = runtimeStore.list(); renderRuntimeProfiles(); renderCores(); form.reset(); form.elements.platform.value = 'any'; form.elements.trust.value = 'user-approved'; toast('Runtime profile saved as metadata only.'); } catch (error) { toast(error.message); } });
runtimeList.addEventListener('click', event => { const button = event.target.closest('[data-remove-runtime]'); if (!button) return; state.runtimeProfiles = runtimeStore.remove(button.dataset.removeRuntime); renderRuntimeProfiles(); renderCores(); toast('Runtime profile removed.'); });
document.querySelector('[data-game-files]').addEventListener('change', event => addFiles(event.target.files, 'game'));
document.querySelector('[data-firmware-files]').addEventListener('change', event => addFiles(event.target.files, 'firmware'));
document.querySelector('[data-clear-library]').addEventListener('click', () => { state.rememberedFiles = library.clear(); renderRememberedFiles(); toast('Remembered collection cleared'); });
document.querySelector('[data-library-list]').addEventListener('click', event => { const button = event.target.closest('[data-remove-library]'); if (!button) return; state.rememberedFiles = library.remove(button.dataset.removeLibrary); renderRememberedFiles(); toast('File metadata forgotten'); });
state.rememberedFiles = library.list();
loadCores();
renderFiles();
renderRememberedFiles();
renderRuntimeProfiles();
