import test from 'node:test';
import assert from 'node:assert/strict';
import {createProviderIntegration, providerTroubleshooting} from './integration.mjs';

const xbox = {id: 'xbox-cloud-gaming', name: 'Xbox Cloud Gaming', backendType: 'provider', integrationModes: ['browser-first', 'official-launch'], capabilities: ['gamepad', 'touch-controls'], requirements: ['xbox-account'], url: 'https://www.xbox.com/play'};
const stream = {id: 'twitch', name: 'Twitch', backendType: 'provider', integrationModes: ['browser-first', 'official-api', 'official-embed'], capabilities: ['video', 'chat'], requirements: [], url: 'https://www.twitch.tv/'};

test('provider integration selects platform preset and saved launch preference', () => { const integration = createProviderIntegration(xbox, {profile: {launchMode: 'official', quality: 'prefer-latency', region: 'north-america', autoFullscreen: true}}); assert.equal(integration.mode, 'official-launch'); assert.equal(integration.controllerProfile, 'Xbox layout'); assert.equal(integration.quality, 'prefer-latency'); assert.equal(integration.regionLabel, 'North America'); assert.equal(integration.autoFullscreen, true); assert.match(integration.notes.at(-1), /Fullscreen/); });
test('provider integration exposes official surfaces without claiming API access', () => { const integration = createProviderIntegration(stream); assert.equal(integration.mode, 'browser-first'); assert.deepEqual(integration.surfaces, ['video', 'chat']); assert.equal(integration.health.authenticated, false); });
test('provider integration applies conservative presets to major services', () => { const integration = createProviderIntegration({...xbox, id: 'nvidia-geforce-now', capabilities: ['gamepad']}); assert.equal(integration.controllerProfile, 'Auto-detect'); assert.equal(integration.quality, 'prefer-latency'); });
test('provider integration bounds unknown region hints to automatic', () => { const integration = createProviderIntegration(xbox, {profile: {region: 'mars'}}); assert.equal(integration.regionHint, 'automatic'); assert.equal(integration.regionLabel, 'Automatic'); });
test('provider integration builds and selects official target-aware embeds', () => { const twitch = createProviderIntegration({...stream, id: 'twitch'}, {profile: {embedTarget: 'twitchdev', embedParent: 'gaming.example'}}); assert.equal(twitch.mode, 'official-embed'); assert.match(twitch.embedUrl, /player\.twitch\.tv/); assert.match(twitch.embedUrl, /parent=gaming\.example/); const local = createProviderIntegration({...stream, id: 'twitch'}, {profile: {embedTarget: 'twitchdev', embedParent: 'localhost'}}); assert.equal(local.mode, 'official-embed'); const youtube = createProviderIntegration({...stream, id: 'youtube-live'}, {profile: {embedTarget: 'M7lc1UVf-VE'}}); assert.equal(youtube.mode, 'official-embed'); assert.equal(youtube.embedUrl, 'https://www.youtube.com/embed/M7lc1UVf-VE'); const kick = createProviderIntegration({...stream, id: 'kick'}, {profile: {embedTarget: 'spartanlive'}}); assert.equal(kick.mode, 'official-embed'); assert.equal(kick.embedUrl, 'https://player.kick.com/spartanlive'); assert.equal(createProviderIntegration({...stream, id: 'kick'}, {profile: {embedTarget: 'not valid'}}).embedUrl, null); assert.equal(createProviderIntegration(stream, {profile: {embedTarget: 'not valid'}}).embedUrl, null); });
test('provider troubleshooting remains structured and capability-aware', () => { const integration = createProviderIntegration(xbox, {report: {input: {gamepad: false}}}); const issues = providerTroubleshooting(integration); assert.equal(issues[0].key, 'gamepad'); assert.equal(issues[1].key, 'configuration'); });
