import {
  CONTROLLER_PROFILE_OPTIONS,
  isControllerProfileSelection,
} from '../input/controller-policy.mjs';
import { GLOBAL_SHORTCUT_OPTIONS } from './electron-runtime.mjs';

const toggle = (key, label, description, defaultValue = false) => ({
  key,
  label,
  description,
  type: 'toggle',
  default: defaultValue,
});
const select = (key, label, description, options, defaultValue) => ({
  key,
  label,
  description,
  type: 'select',
  options,
  default: defaultValue ?? options[0],
});
const range = (key, label, description, min, max, step, defaultValue, unit = '') => ({
  key,
  label,
  description,
  type: 'range',
  min,
  max,
  step,
  default: defaultValue,
  unit,
});
const text = (key, label, description, defaultValue = '') => ({
  key,
  label,
  description,
  type: 'text',
  default: defaultValue,
});
const secret = (key, label, description, defaultValue = '') => ({
  key,
  label,
  description,
  type: 'secret',
  default: defaultValue,
});
const action = (key, label, description, actionLabel) => ({
  key,
  label,
  description,
  type: 'action',
  actionLabel,
});

export const settingsCategories = [
  {
    id: 'general',
    label: 'General',
    icon: '◈',
    description: 'Startup, defaults, and standalone application behavior.',
    settings: [
      toggle(
        'general.restoreSession',
        'Restore previous session',
        'Restore the active workspace and eligible game-session handoff on startup.',
        true,
      ),
      toggle(
        'session.autoLogin',
        'Auto-login to last host',
        'Remember the last authenticated host session in this app and reconnect automatically on the next launch. The handoff is stored only in the local app profile with a 30-day expiry; Spartan never reads logins from another browser.',
      ),
      select(
        'general.startupPage',
        'Startup page',
        'Choose what Spartan Gaming opens when the application launches.',
        ['Gaming home', 'Continue playing', 'New session', 'Last session'],
        'Gaming home',
      ),
      toggle(
        'general.askBeforeQuit',
        'Confirm before quitting',
        'Prevent accidental shutdown while an active session is running.',
        true,
      ),
      toggle(
        'general.backgroundApps',
        'Continue background apps',
        'Keep the Electron process available after the window closes for configured background tasks.',
      ),
      select(
        'general.globalShortcut',
        'Desktop global shortcut',
        'Optionally register a system-wide shortcut that restores and focuses Spartan Gaming. Registration remains disabled by default and may be unavailable when another application owns the shortcut.',
        GLOBAL_SHORTCUT_OPTIONS,
        'Disabled',
      ),
      select(
        'general.language',
        'Language',
        'Interface language. Provider content remains controlled by the provider.',
        ['English', 'Spanish', 'French', 'German', 'Japanese', 'Korean'],
        'English',
      ),
      action(
        'general.reset',
        'Reset all settings',
        'Restore Spartan Gaming defaults. Local profiles and saved games are not removed.',
        'Reset settings',
      ),
    ],
  },
  {
    id: 'appearance',
    label: 'Appearance',
    icon: '◐',
    description: 'Theme, layout, density, and fullscreen presentation.',
    settings: [
      select(
        'appearance.theme',
        'Theme',
        'Choose the visual treatment for browser chrome and the gaming frontend.',
        ['Spartan Dark', 'Spartan Light', 'System', 'OLED Black'],
        'Spartan Dark',
      ),
      select(
        'appearance.accent',
        'Accent color',
        'Used for focus, active controls, selection, and session status.',
        ['Cyan', 'Violet', 'Lime', 'Amber', 'Red', 'Custom'],
        'Cyan',
      ),
      select(
        'appearance.density',
        'Interface density',
        'Controls spacing in navigation, library rows, and settings.',
        ['Comfortable', 'Compact', 'Controller-first'],
        'Comfortable',
      ),
      select(
        'appearance.deviceMode',
        'Device presentation mode',
        'Tune navigation, focus targets, touch controls, fullscreen, and layout for the current device class.',
        ['Automatic', 'Desktop', 'ChromeOS', 'Handheld', 'Mobile', 'Television'],
        'Automatic',
      ),
      toggle(
        'appearance.consoleMode',
        'Console mode',
        'Use a controller-first, fullscreen-friendly dashboard presentation with larger focus targets.',
        false,
      ),
      select(
        'appearance.tabLayout',
        'Tab layout',
        'Choose how browser tabs are presented during normal browsing.',
        ['Top tabs', 'Vertical tabs', 'Compact tabs', 'Hidden in gaming mode'],
        'Top tabs',
      ),
      toggle(
        'appearance.translucentChrome',
        'Translucent browser chrome',
        'Use a subtle translucent surface where the platform compositor supports it.',
        true,
      ),
      toggle(
        'appearance.reduceMotion',
        'Reduce motion',
        'Respect reduced-motion preferences and remove non-essential transitions.',
      ),
      toggle(
        'appearance.showStatusBar',
        'Show session status bar',
        'Keep latency, controller, and connection state visible below the game.',
      ),
      range(
        'appearance.uiScale',
        'UI scale',
        'Scale browser controls and the gaming overlay independently of page zoom.',
        80,
        140,
        5,
        100,
        '%',
      ),
    ],
  },
  {
    id: 'television',
    label: 'Television',
    icon: '▣',
    description: 'Remote navigation, safe areas, and living-room presentation.',
    settings: [
      select(
        'television.remoteNavigationSpeed',
        'Remote navigation speed',
        'Control how often Fire TV, Roku, and other television targets poll a connected controller.',
        ['Automatic', 'Responsive', 'Balanced', 'Low power'],
        'Automatic',
      ),
      toggle(
        'television.focusWrap',
        'Wrap remote focus',
        'Move focus to the opposite edge when directional navigation reaches the end of a row or page.',
        true,
      ),
      range(
        'television.remoteDeadzone',
        'Remote stick dead zone',
        'Ignore small analog movement while navigating television menus.',
        15,
        60,
        1,
        35,
        '%',
      ),
      toggle(
        'television.showPointer',
        'Show pointer on television',
        'Keep a pointer visible for television browsers that expose mouse or touch input.',
        false,
      ),
      range(
        'television.safeArea',
        'Television safe area',
        'Inset content to protect controls from overscan and rounded-corner clipping.',
        0,
        10,
        1,
        5,
        '%',
      ),
      toggle(
        'television.autoHideChrome',
        'Hide browser chrome on television',
        'Prefer a clean living-room presentation when the television target enters fullscreen.',
        true,
      ),
    ],
  },
  {
    id: 'mobile',
    label: 'Android mobile',
    icon: '▤',
    description: 'Phone, tablet, foldable, and handheld playback behavior.',
    settings: [
      select(
        'mobile.orientation',
        'Preferred orientation',
        'Choose the orientation requested when a mobile game session enters fullscreen.',
        ['Automatic', 'Landscape', 'Portrait'],
        'Automatic',
      ),
      toggle(
        'mobile.keepScreenAwake',
        'Keep screen awake during sessions',
        'Request a wake lock while an active game session is playing; Android may still revoke it for system policy.',
        true,
      ),
      toggle(
        'mobile.pictureInPicture',
        'Allow Picture-in-Picture',
        'Allow an Android shell to continue stream playback in a system PiP window when supported.',
        true,
      ),
      toggle(
        'mobile.edgeToEdge',
        'Use edge-to-edge layout',
        'Let the mobile shell draw behind system bars while preserving safe areas for touch controls.',
        true,
      ),
      toggle(
        'mobile.dataSaver',
        'Mobile data saver',
        'Prefer lower bandwidth and conservative recovery behavior on metered mobile networks.',
        false,
      ),
      select(
        'mobile.gameMode',
        'Android Game Mode intent',
        'Tell the Android shell whether to request standard, performance, or battery-oriented game behavior.',
        ['Follow system', 'Performance', 'Battery', 'Standard'],
        'Follow system',
      ),
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    icon: '✦',
    description: 'Library, launch behavior, overlays, and game sessions.',
    settings: [
      toggle(
        'gaming.autoFullscreen',
        'Enter fullscreen on launch',
        'Request fullscreen when a provider or emulator session begins.',
        true,
      ),
      toggle(
        'gaming.hideBrowserChrome',
        'Hide browser chrome in sessions',
        'Remove tabs and navigation controls while a game session is active.',
        true,
      ),
      toggle(
        'gaming.pauseOnBlur',
        'Pause when window loses focus',
        'Ask the backend to pause when another application becomes active.',
      ),
      select(
        'gaming.launchBehavior',
        'Launch behavior',
        'Choose where new games open.',
        ['Current workspace', 'New tab', 'New gaming window', 'Fullscreen window'],
        'Current workspace',
      ),
      select(
        'gaming.sessionPriority',
        'Session priority',
        'Control how Spartan Gaming treats game processes and background tabs.',
        ['Balanced', 'Game priority', 'Maximum game priority'],
        'Game priority',
      ),
      toggle(
        'gaming.autoSuspendTabs',
        'Suspend unrelated tabs',
        'Reduce memory and CPU use while a session is active.',
        true,
      ),
      toggle(
        'gaming.showOverlay',
        'Enable gaming overlay',
        'Allow the session overlay for quality, input, capture, chat, and controls.',
        true,
      ),
      toggle(
        'gaming.pictureInPicture',
        'Allow Picture-in-Picture',
        'Keep a live game stream visible in a floating browser window while browsing other pages.',
        true,
      ),
      select(
        'gaming.overlayPosition',
        'Overlay position',
        'Default location for the session overlay.',
        ['Top left', 'Top right', 'Bottom left', 'Bottom right'],
        'Top right',
      ),
      range(
        'gaming.overlayOpacity',
        'Overlay opacity',
        'Opacity of the session overlay surface.',
        20,
        100,
        5,
        92,
        '%',
      ),
      toggle(
        'gaming.instantReplay',
        'Enable instant replay buffer',
        'Keep a rolling local buffer for clipping the last moments of a session.',
      ),
      select(
        'gaming.replayLength',
        'Replay length',
        'How much video the instant replay buffer retains.',
        ['15 seconds', '30 seconds', '60 seconds', '120 seconds'],
        '30 seconds',
      ),
    ],
  },
  {
    id: 'streaming',
    label: 'Streaming',
    icon: '◉',
    description: 'Cloud playback, remote play, and stream quality.',
    settings: [
      select(
        'streaming.qualityPreset',
        'Quality preset',
        'Choose the default tradeoff between image quality, bandwidth, and latency.',
        ['Prefer latency', 'Balanced', 'Prefer quality', 'Custom'],
        'Balanced',
      ),
      select(
        'streaming.resolution',
        'Maximum resolution',
        'The highest output resolution requested from a provider or host.',
        ['720p', '1080p', '1440p', '4K', 'Source'],
        '1080p',
      ),
      select(
        'streaming.framerate',
        'Maximum framerate',
        'Cap the stream framerate to match the display and network.',
        ['30 FPS', '60 FPS', '90 FPS', '120 FPS', '144 FPS'],
        '60 FPS',
      ),
      range(
        'streaming.bitrate',
        'Bitrate limit',
        'Maximum target video bitrate. Providers may apply their own limits.',
        2,
        100,
        1,
        25,
        ' Mbps',
      ),
      select(
        'streaming.codec',
        'Preferred codec',
        'Codec preference sent during negotiation. Automatic falls back safely.',
        ['Automatic', 'AV1', 'VP9', 'H.264'],
        'Automatic',
      ),
      toggle(
        'streaming.hardwareDecode',
        'Prefer hardware video decoding',
        'Use the platform decoder when it is available and stable.',
        true,
      ),
      toggle(
        'streaming.adaptiveBitrate',
        'Adaptive bitrate',
        'Adjust bitrate based on congestion, packet loss, and decode health.',
        true,
      ),
      toggle(
        'streaming.adaptiveResolution',
        'Adaptive resolution',
        'Lower resolution before the session starts dropping frames.',
        true,
      ),
      toggle(
        'streaming.lowLatencyMode',
        'Low-latency mode',
        'Reduce buffering and jitter tolerance at the cost of more visible recovery.',
        true,
      ),
      range(
        'streaming.jitterBuffer',
        'Jitter buffer',
        'Additional receive buffer for unstable connections.',
        0,
        500,
        10,
        60,
        ' ms',
      ),
      select(
        'streaming.networkMode',
        'Network mode',
        'Choose congestion behavior for wired, Wi-Fi, or metered networks.',
        ['Automatic', 'Wired', 'Wi-Fi', 'Mobile/metered'],
        'Automatic',
      ),
      select(
        'streaming.transportPreference',
        'Transport preference',
        'Choose the preferred session transport. Automatic prefers WebRTC and falls back safely.',
        ['Automatic', 'WebRTC', 'WebTransport experimental', 'WebSocket fallback'],
        'Automatic',
      ),
      select(
        'streaming.icePolicy',
        'ICE connectivity policy',
        'Use direct and relay candidates, or require a relay for privacy and restrictive networks.',
        ['All candidates', 'Relay only'],
        'All candidates',
      ),
      toggle(
        'streaming.allowWebTransport',
        'Allow WebTransport',
        'Allow compatible self-hosted sessions to use experimental WebTransport datagrams.',
        true,
      ),
      toggle(
        'streaming.allowWebSocketFallback',
        'Allow WebSocket fallback',
        'Keep signaling available when WebRTC or WebTransport cannot connect.',
        true,
      ),
      toggle(
        'streaming.showTelemetry',
        'Show stream telemetry',
        'Expose ping, jitter, packet loss, decode time, and frame pacing.',
      ),    ],
  },
  {
    id: 'social',
    label: 'Social Center',
    icon: '◍',
    description: 'Friends, parties, streaming status, and notifications.',
    settings: [
      toggle(
        'social.showOnlineStatus',
        'Show online status',
        'Let friends see when you are online.',
        true,
      ),
      toggle(
        'social.showActivity',
        'Show activity',
        'Share what you are playing with friends.',
        true,
      ),
      toggle(
        'social.enableNotifications',
        'Enable notifications',
        'Receive friend requests, party invites, and social alerts.',
        true,
      ),
      toggle(
        'social.allowFriendRequests',
        'Allow friend requests',
        'Let other players send you friend requests.',
        true,
      ),
      toggle(
        'social.autoJoinParty',
        'Auto-join party invites',
        'Automatically join parties when invited by friends.',
      ),
    ],
  },
  {
    id: 'multiplayer',
    label: 'Multiplayer',
    icon: '♟',
    description: 'Game sessions, netplay, and session coordination.',
    settings: [
      toggle(
        'multiplayer.netplay',
        'Enable netplay',
        'Allow multiplayer networking for cores and adapters that support it.',
      ),
      toggle(
        'multiplayer.allowInvitations',
        'Allow invitations',
        'Let friends invite you to multiplayer sessions.',
        true,
      ),
      toggle(
        'multiplayer.showInLobby',
        'Show in lobby',
        'Make your sessions visible in the public multiplayer lobby.',
      ),
      select(
        'multiplayer.defaultMaxPlayers',
        'Default max players',
        'Default maximum number of players for new sessions.',
        ['2', '4', '8', '16', '32', '64'],
        '4',
      ),
      toggle(
        'multiplayer.autoSpectate',
        'Auto-spectate when full',
        'Automatically spectate when a session reaches maximum players.',
      ),    ],
  },
  {
    id: 'accounts',
    label: 'Accounts & API',
    icon: '▤',
    description: 'Connection preferences and optional credentials used by approved integrations.',
    settings: [
      text(
        'accounts.defaultLogin',
        'Default login label',
        'A local label for the account you use most often. Spartan Gaming never asks for a provider password here.',
        '',
      ),
      select(
        'accounts.loginMode',
        'Login handoff',
        'Choose how provider sign-in is handled when a service opens.',
        ['Official service in Spartan Gaming', 'System browser handoff', 'Ask every time'],
        'Official service in Spartan Gaming',
      ),
      text(
        'accounts.syncEndpoint',
        'Self-hosted sync endpoint',
        'Optional HTTPS endpoint for your own Spartan sync service.',
        '',
      ),
      secret(
        'accounts.syncApiKey',
        'Self-hosted sync API key',
        'Optional API key for the self-hosted sync endpoint. Stored only in this local profile; clear it when you finish setup.',
        '',
      ),
      text(
        'accounts.hostEndpoint',
        'Default host endpoint',
        'Optional user-owned Spartan Host endpoint used for remote play.',
        '',
      ),
      secret(
        'accounts.hostApiKey',
        'Host API key',
        'Optional API key for your user-owned host. It is never exported with settings.',
        '',
      ),
      text(
        'accounts.providerClientId',
        'Provider client ID',
        'Optional OAuth client ID for a provider integration that explicitly documents custom clients.',
        '',
      ),
      secret(
        'accounts.providerApiKey',
        'Provider API key',
        'Optional API key for provider APIs such as catalog or creator tools. Only enter keys supplied by the official provider.',
        '',
      ),
      action(
        'accounts.clearCredentials',
        'Clear saved credentials',
        'Remove all optional API keys and login labels from this local profile.',
        'Clear credentials',
      ),
    ],
  },
  {
    id: 'controllers',
    label: 'Controllers',
    icon: '⌁',
    description: 'Gamepads, HID devices, mappings, and rumble.',
    settings: [
      {
        ...select(
          'controllers.defaultProfile',
          'Default controller profile',
          'Profile used for new games and providers. Custom profiles created in the profile manager appear here by their stable local ID.',
          CONTROLLER_PROFILE_OPTIONS,
          'Auto-detect',
        ),
        accepts: isControllerProfileSelection,
      },
      select(
        'controllers.inputMode',
        'Controller input mode',
        'Select how connected controllers are exposed to games and remote hosts.',
        ['Auto-detect', 'XInput', 'DirectInput', 'Standard Gamepad', 'HID passthrough'],
        'Auto-detect',
      ),
      select(
        'controllers.glyphStyle',
        'Controller glyph style',
        'Choose portable button labels when an official Steam Input glyph bridge is unavailable.',
        ['Automatic', 'Xbox', 'PlayStation', 'Nintendo', 'Steam'],
        'Automatic',
      ),
      select(
        'controllers.virtualGamepadBackend',
        'Virtual gamepad backend',
        'Choose the native or externally installed bridge used when a host or game needs a virtual controller; unavailable bridges fail closed. Windows and macOS require an operator-installed external driver.',
        [
          'Automatic',
          'Browser Gamepad',
          'Linux uinput',
          'Windows external driver',
          'macOS external driver',
          'Disabled',
        ],
        'Automatic',
      ),
      text(
        'controllers.virtualGamepadPackage',
        'Virtual gamepad driver package',
        'Optional installed host adapter package for Windows or macOS virtual-controller injection. Package names are passed to the user-owned host only; no driver is downloaded automatically.',
        '',
      ),
      text(
        'controllers.virtualGamepadDevice',
        'Virtual gamepad device ID',
        'Optional driver-specific device identifier for multi-device or multi-controller setups. Leave blank for automatic selection.',
        '',
      ),
      text(
        'controllers.virtualGamepadDevices',
        'Virtual gamepad device IDs',
        'Optional comma-separated device IDs mapped to controller slots 1–8. Leave blank to use the single device ID or automatic selection.',
        '',
      ),
      select(
        'controllers.hapticsBackend',
        'Haptics backend',
        'Choose browser or native rumble output for supported controllers.',
        ['Automatic', 'Browser vibration', 'Native rumble', 'Disabled'],
        'Automatic',
      ),
      toggle(
        'controllers.multipleControllers',
        'Allow multiple controllers',
        'Expose more than one connected controller to multiplayer games and hosts.',
        true,
      ),
      select(
        'controllers.playerSlots',
        'Controller player slots',
        'Maximum number of controller slots available to a session.',
        ['1', '2', '4', '8'],
        '4',
      ),
      toggle(
        'controllers.allowGamepad',
        'Allow gamepads',
        'Allow web sessions and adapters to access connected gamepads.',
        true,
      ),
      toggle(
        'controllers.allowHid',
        'Allow HID devices',
        'Allow explicitly approved racing wheels, fight sticks, flight sticks, and specialty controllers.',
      ),
      toggle(
        'controllers.rumble',
        'Enable rumble',
        'Forward vibration and haptic feedback when supported.',
        true,
      ),
      toggle(
        'controllers.adaptiveTriggers',
        'Enable adaptive triggers',
        'Forward adaptive trigger effects where the platform and backend support them.',
      ),
      toggle(
        'controllers.gyro',
        'Enable motion controls',
        'Allow gyroscope and accelerometer input for compatible games.',
      ),
      toggle(
        'controllers.touchpad',
        'Enable touchpads',
        'Forward DualSense, Steam Deck, and compatible touchpad gestures when supported.',
      ),
      toggle(
        'controllers.trackpads',
        'Enable trackpads',
        'Forward Steam Deck and Steam Controller trackpad motion/clicks when supported.',
      ),
      toggle(
        'controllers.backButtons',
        'Enable rear buttons',
        'Forward Steam Deck, Xbox Elite, and compatible rear-paddle controls.',
      ),
      toggle(
        'controllers.touchscreen',
        'Enable touchscreen input',
        'Forward touchscreen taps and gestures for handheld navigation when supported.',
      ),
      toggle(
        'controllers.textEntry',
        'Enable controller text entry',
        'Allow supported handheld controllers to request on-screen text entry; the platform still controls the keyboard UI.',
        true,
      ),
      toggle(
        'controllers.controllerNavigation',
        'Enable controller-only navigation',
        'Allow gamepad focus navigation for Steam Deck, television, and other controller-first surfaces.',
        true,
      ),
      select(
        'controllers.triggerMode',
        'Trigger mode',
        'Expose analog triggers, digital buttons, or both where supported.',
        ['Analog and digital', 'Analog only', 'Digital only'],
        'Analog and digital',
      ),
      range(
        'controllers.steeringRange',
        'Steering range',
        'Virtual steering rotation for wheels and analog steering devices.',
        90,
        1080,
        10,
        900,
        '°',
      ),
      toggle(
        'controllers.splitInput',
        'Allow split controller input',
        'Permit two physical halves or devices to form one virtual controller.',
        false,
      ),
      range(
        'controllers.deadzone',
        'Default stick dead zone',
        'Ignore small analog stick movement to reduce drift.',
        0,
        30,
        1,
        8,
        '%',
      ),
      select(
        'controllers.inputLatency',
        'Input polling',
        'Controller polling target; platform and device limits still apply.',
        ['Automatic', 'Standard', 'High frequency'],
        'Automatic',
      ),
      action(
        'controllers.manageProfiles',
        'Manage controller profiles',
        'Create, edit, import, and export per-device and per-game mappings.',
        'Open profile manager',
      ),
      action(
        'controllers.test',
        'Test connected devices',
        'Inspect buttons, axes, haptics, battery, and motion sensors.',
        'Open controller tester',
      ),
    ],
  },
  {
    id: 'emulation',
    label: 'Emulation',
    icon: '⌘',
    description: 'Cores, adapters, saves, shaders, and legal file access.',
    settings: [
      select(
        'emulation.frontend',
        'Emulation frontend',
        'Choose the runtime used for compatible cores and standalone adapters.',
        ['Automatic', 'Spartan runtime', 'Libretro host', 'Native adapter'],
        'Automatic',
      ),
      select(
        'emulation.windowsCompatibility',
        'Windows emulator compatibility',
        'Linux fallback for Windows-only emulator builds. Wine is deterministic; PlayOnLinux manages named Wine prefixes.',
        ['Automatic', 'Wine', 'PlayOnLinux', 'Disabled'],
        'Automatic',
      ),
      toggle(
        'emulation.scanLibraries',
        'Scan selected game folders',
        'Index user-selected folders for supported games and metadata.',
        true,
      ),
      toggle(
        'emulation.autoSaveStates',
        'Auto-save on exit',
        'Create a safety save state when a session closes normally.',
        true,
      ),
      toggle(
        'emulation.cloudSaves',
        'Sync save data',
        'Sync save RAM and save states through the selected sync provider.',
      ),
      select(
        'emulation.saveLocation',
        'Save location',
        'Where local save data is stored.',
        ['Profile storage', 'Game folder', 'Custom folder'],
        'Profile storage',
      ),
      select(
        'emulation.renderer',
        'Graphics renderer',
        'Default renderer for native adapters and compatible cores.',
        ['Automatic', 'Vulkan', 'DirectX 12', 'Metal', 'OpenGL', 'Software'],
        'Automatic',
      ),
      toggle(
        'emulation.integerScaling',
        'Integer scaling',
        'Preserve sharp pixel edges for low-resolution systems.',
        true,
      ),
      toggle(
        'emulation.vsync',
        'Vertical synchronization',
        'Synchronize emulated frames to the display refresh cycle.',
        true,
      ),
      select(
        'emulation.shaderPreset',
        'Shader preset',
        'Default post-processing for emulated video.',
        ['Off', 'Sharp bilinear', 'CRT subtle', 'CRT scanlines', 'LCD'],
        'Sharp bilinear',
      ),
      toggle(
        'emulation.rewind',
        'Enable rewind',
        'Keep a rolling state buffer for supported cores.',
      ),
      toggle(
        'emulation.netplay',
        'Allow netplay',
        'Enable multiplayer networking for cores and adapters that support it.',
      ),
      action(
        'emulation.importFirmware',
        'Import BIOS or firmware',
        'Select and hash-check firmware you legally dumped from your own hardware.',
        'Import firmware',
      ),
      action(
        'emulation.manageCores',
        'Manage emulator cores',
        'View installed cores, versions, licenses, and update channels.',
        'Open core manager',
      ),
    ],
  },
  {
    id: 'providers',
    label: 'Providers',
    icon: '◇',
    description: 'Cloud services, accounts, regions, and compatibility profiles.',
    settings: [
      toggle(
        'providers.showCatalog',
        'Show provider catalog',
        'Include supported cloud, remote-play, and streaming providers in the library.',
        true,
      ),
      toggle(
        'providers.autoDetect',
        'Detect provider sessions',
        'Treat loaded supported provider views as active sessions for power and quit behavior.',
        true,
      ),
      toggle(
        'providers.preferOfficialApps',
        'Prefer official native apps',
        'Launch a provider’s official app when browser support is unavailable or explicitly preferred.',
      ),
      toggle(
        'providers.gameNativeCompanion',
        'Enable GameNative Android companion',
        'Show the official GameNative Android companion in the provider catalog. Spartan Gaming opens the official site or release page; installation and account access remain user-mediated.',
        true,
      ),
      select(
        'providers.gameNativeStore',
        'GameNative library source',
        'Choose the store families to surface when preparing a GameNative Android session.',
        ['Steam', 'Epic', 'GOG', 'Amazon', 'All supported stores'],
        'All supported stores',
      ),
      select(
        'providers.region',
        'Service region',
        'Region hint used for links, latency tests, and provider recommendations.',
        ['Automatic', 'North America', 'Europe', 'Asia Pacific', 'Latin America', 'Custom'],
        'Automatic',
      ),
      toggle(
        'providers.healthChecks',
        'Run provider health checks',
        'Test provider reachability and compatibility without signing in.',
      ),
      toggle(
        'providers.librarySync',
        'Sync provider libraries',
        'Use approved account integrations to show owned or available games.',
      ),
      toggle(
        'providers.isolateAccounts',
        'Isolate provider accounts by profile',
        'Prevent account metadata and sessions from crossing local gaming profiles.',
        true,
      ),
      toggle(
        'providers.autoLogin',
        'Retain cloud service sign-ins',
        'Keep cloud gaming service sign-ins inside the desktop app and sign in automatically on later launches. Disable to start each provider session signed out using an in-memory session.',
        true,
      ),
      action(
        'providers.manageProfiles',
        'Manage provider profiles',
        'Configure launch URLs, account profiles, region hints, and quality overrides.',
        'Open provider manager',
      ),
      action(
        'providers.manageHosts',
        'Manage self-hosted machines',
        'Register user-owned PCs and prepare secure, expiring pairing requests.',
        'Open host manager',
      ),
      action(
        'providers.clearSessions',
        'Clear provider logins and sessions',
        'Sign out of providers stored in the desktop app and remove Spartan launch, recovery, and pairing handoffs.',
        'Clear logins',
      ),
    ],
  },
  {
    id: 'host',
    label: 'Self-hosted play',
    icon: '⌂',
    description: 'Capture, encoding, pairing, wake, and input settings for user-owned hosts.',
    settings: [
      select(
        'host.captureSource',
        'Capture source',
        'Display or window source exposed by a user-owned host.',
        ['Automatic', 'Primary display', 'Selected display', 'Selected window'],
        'Automatic',
      ),
      select(
        'host.videoCodec',
        'Host video codec',
        'Preferred host encoder codec; actual availability is negotiated from the host hardware.',
        ['Automatic', 'H.264', 'VP9', 'AV1', 'HEVC'],
        'Automatic',
      ),
      select(
        'host.maxResolution',
        'Host maximum resolution',
        'Upper bound for host capture and encoded output.',
        ['720p', '1080p', '1440p', '4K', 'Source'],
        '1080p',
      ),
      select(
        'host.maxFramerate',
        'Host maximum framerate',
        'Upper bound for host capture and encoded output.',
        ['30 FPS', '60 FPS', '90 FPS', '120 FPS', '144 FPS'],
        '60 FPS',
      ),
      toggle(
        'host.captureSystemAudio',
        'Capture system audio',
        'Return game audio from the user-owned host when the platform grants capture access.',
        true,
      ),
      toggle(
        'host.captureMicrophone',
        'Capture host microphone',
        'Allow an explicitly selected host microphone to be shared with a session.',
        false,
      ),
      select(
        'host.audioCodec',
        'Host audio codec',
        'Audio codec requested for host-to-player return audio.',
        ['Automatic', 'Opus', 'AAC'],
        'Automatic',
      ),
      text(
        'host.nativePackage',
        'Native host package',
        'Optional installed platform package used for capture, audio, and OS input. The host never downloads packages from this setting.',
        '',
      ),
      toggle(
        'host.protonEnabled',
        'Enable Proton launches',
        'Allow the user-owned Linux/SteamOS host to launch Windows games through an explicitly selected Proton installation.',
        false,
      ),
      text(
        'host.protonPath',
        'Proton executable path',
        'Host-local path to the selected Proton installation executable; Spartan never downloads or bundles Proton.',
        '',
      ),
      text(
        'host.protonVersion',
        'Proton version label',
        'Optional version label used in host readiness and launch diagnostics.',
        '',
      ),
      text(
        'host.protonCompatDataPath',
        'Proton compatibility prefix',
        'Host-local STEAM_COMPAT_DATA_PATH directory for the selected game; keep it outside the repository.',
        '',
      ),
      text(
        'host.protonSteamClientPath',
        'Steam client path',
        'Optional host-local Steam installation path used by Proton for user-owned Steam integration.',
        '',
      ),
      text(
        'host.protonEnvironment',
        'Proton runtime options',
        'Optional JSON object containing allow-listed Proton options such as PROTON_LOG or PROTON_USE_WINED3D; arbitrary environment variables are rejected.',
        '',
      ),
      toggle(
        'host.steamOsEnabled',
        'SteamOS host profile',
        'Declare that the selected Linux host is an explicitly detected SteamOS environment; generic Linux hosts remain generic Linux.',
        false,
      ),
      select(
        'host.steamOsMode',
        'SteamOS session mode',
        'Choose the intended SteamOS session surface for diagnostics and launch planning.',
        ['Game Mode', 'Desktop Mode'],
        'Game Mode',
      ),
      toggle(
        'host.gamescopeEnabled',
        'Use Gamescope launch wrapper',
        'Plan a user-selected Gamescope wrapper with the bounded 1280×800 handheld profile; physical host validation is required.',
        false,
      ),
      select(
        'host.steamOsFramerate',
        'SteamOS handheld framerate',
        'Bound the SteamOS handheld profile to the documented 30, 40, or 60 FPS choices.',
        ['30 FPS', '40 FPS', '60 FPS'],
        '60 FPS',
      ),
      select(
        'host.steamInputMode',
        'Steam Input integration',
        'Use official Steam action metadata when a bridge supplies it, otherwise retain the shared Gamepad/HID fallback.',
        ['Fallback Gamepad/HID', 'Official action metadata'],
        'Fallback Gamepad/HID',
      ),
      select(
        'host.steamOsLaunchMode',
        'SteamOS launch mode',
        'Choose native Linux, Proton, Steam-owned, or non-Steam launch metadata; readiness remains explicit until a host bridge is installed.',
        ['Native Linux', 'Proton', 'Steam-owned', 'Non-Steam'],
        'Native Linux',
      ),
      text(
        'host.steamAppId',
        'Steam app ID',
        'Optional numeric Steam app ID for a future user-approved Steam handoff; no Steam credentials are stored.',
        '',
      ),
      text(
        'host.virtualGamepadInstallRoot',
        'Virtual gamepad install root',
        'Host-local directory containing verified virtual-gamepad adapter packages. This path is used only when exporting host configuration.',
        '',
      ),
      text(
        'host.virtualGamepadAdapterId',
        'Virtual gamepad adapter ID',
        'Stable ID of the verified virtual-gamepad adapter package installed on the host.',
        '',
      ),
      toggle(
        'host.enableNativeMedia',
        'Enable native host media',
        'Allow a configured native host package and WebRTC adapter to publish display video.',
        false,
      ),
      toggle(
        'host.enableNativeAudio',
        'Enable native host audio',
        'Allow a configured native host package to return explicitly permitted host audio.',
        false,
      ),
      text(
        'host.audioSource',
        'Host audio source',
        'Optional platform-specific capture source passed to the user-owned host.',
        '',
      ),
      select(
        'host.audioBackend',
        'Host audio backend',
        'Audio API selected by the user-owned host.',
        ['Automatic', 'PipeWire', 'PulseAudio', 'WASAPI', 'CoreAudio'],
        'Automatic',
      ),
      toggle(
        'host.allowInputInjection',
        'Allow input injection',
        'Permit the paired session to send controller, keyboard, pointer, and haptic events to the host.',
        true,
      ),
      action(
        'host.exportConfig',
        'Export host configuration',
        'Create a portable host.json from host and controller settings without pairing codes or credentials.',
        'Export host.json',
      ),
      toggle(
        'host.requireExplicitPairing',
        'Require explicit pairing',
        'Require an expiring pairing approval for every new device, even for a saved host.',
        true,
      ),
      toggle(
        'host.wakeOnLan',
        'Wake host on launch',
        'Send a configured Wake-on-LAN request before attempting a host session.',
        false,
      ),
      range(
        'host.sessionPort',
        'Host session port',
        'Local or forwarded port used by the host agent; TLS and signaling policy still apply.',
        1024,
        65535,
        1,
        8787,
        '',
      ),
      select(
        'host.logLevel',
        'Host diagnostic detail',
        'Amount of host lifecycle information included in local diagnostics.',
        ['Errors only', 'Connection events', 'Verbose'],
        'Connection events',
      ),
    ],
  },
  {
    id: 'performance',
    label: 'Performance',
    icon: '↯',
    description: 'CPU, GPU, memory, power, and diagnostics.',
    settings: [
      toggle(
        'performance.hardwareAcceleration',
        'Use hardware acceleration',
        'Use the GPU for rendering, compositing, WebGPU, and video.',
        true,
      ),
      select(
        'performance.gpuPreference',
        'GPU preference',
        'Choose which GPU to use on multi-GPU systems. Applies on the next launch.',
        ['Automatic', 'Power saving GPU', 'High performance GPU'],
        'Automatic',
      ),
      select(
        'performance.powerMode',
        'Power mode',
        'Balance performance, fan noise, and battery life.',
        ['Balanced', 'Performance', 'Battery saver'],
        'Balanced',
      ),
      toggle(
        'performance.backgroundThrottling',
        'Throttle background tabs',
        'Reduce background work while preserving active game sessions.',
        true,
      ),
      toggle(
        'performance.prewarmProviders',
        'Prewarm provider connections',
        'Prepare approved provider origins for faster session startup.',
      ),
      toggle(
        'performance.webgpu',
        'Enable WebGPU',
        'Allow browser games and supported runtimes to use WebGPU.',
        true,
      ),
      toggle(
        'performance.webAssemblyThreads',
        'Enable WebAssembly threads',
        'Use shared workers for compatible browser emulators and games.',
        true,
      ),
      select(
        'performance.processModel',
        'Process model',
        'Choose the browser process isolation profile. Applies on the next launch.',
        ['Default', 'Maximum isolation', 'Low memory'],
        'Default',
      ),
      toggle(
        'performance.crashReports',
        'Keep local crash reports',
        'Record bounded Electron renderer and child-process failures locally; nothing is uploaded.',
      ),
      action(
        'performance.taskManager',
        'Open gaming task manager',
        'Inspect CPU, GPU, memory, network, decoder, and per-tab usage.',
        'Open task manager',
      ),
      action(
        'performance.diagnostics',
        'Run compatibility diagnostics',
        'Test GPU, codecs, WebGPU, controllers, audio, and network latency.',
        'Run diagnostics',
      ),
    ],
  },
  {
    id: 'privacy',
    label: 'Privacy & security',
    icon: '▣',
    description: 'Permissions, identity isolation, telemetry, and data controls.',
    settings: [
      select(
        'privacy.trackingProtection',
        'Tracking protection',
        'Block known trackers and reduce cross-site profiling.',
        ['Standard', 'Strict', 'Disabled'],
        'Strict',
      ),
      toggle(
        'privacy.blockThirdPartyCookies',
        'Block third-party cookies',
        'Prevent cross-site cookies unless an explicit exception is configured.',
        true,
      ),
      toggle(
        'privacy.preventWebRtcIpLeak',
        'Limit WebRTC IP exposure',
        'Prefer privacy-preserving WebRTC candidates when compatible with the session.',
      ),
      toggle(
        'privacy.doNotTrack',
        'Send Do Not Track',
        'Ask sites not to track browsing activity.',
      ),
      toggle(
        'privacy.telemetry',
        'Share anonymous product telemetry',
        'Share opt-in aggregate performance and compatibility metrics.',
      ),
      toggle(
        'privacy.sessionTelemetry',
        'Store local session telemetry',
        'Keep detailed latency and decoder data locally for troubleshooting.',
        true,
      ),
      select(
        'privacy.permissionPrompts',
        'Permission prompts',
        'Control how device permissions are requested.',
        ['Ask every time', 'Ask per site', 'Block by default'],
        'Ask per site',
      ),
      toggle(
        'privacy.clearOnExit',
        'Clear session data on exit',
        'Remove temporary session cookies, cache, and provider state when the profile closes.',
      ),
      action(
        'privacy.permissions',
        'Review site permissions',
        'Manage camera, microphone, gamepad, HID, screen capture, and notifications.',
        'Review permissions',
      ),
      action(
        'privacy.exportData',
        'Export privacy data',
        'Export permissions, exceptions, and telemetry settings without credentials.',
        'Export data',
      ),
    ],
  },
  {
    id: 'audio-video',
    label: 'Audio & video',
    icon: '◒',
    description: 'Displays, HDR, audio routing, capture, and recording.',
    settings: [
      select(
        'media.display',
        'Preferred display',
        'Display used for fullscreen sessions and capture.',
        ['Automatic', 'Display 1', 'Display 2', 'Ask each time'],
        'Automatic',
      ),
      select(
        'media.refreshRate',
        'Refresh-rate preference',
        'Target display refresh rate for session negotiation.',
        ['Automatic', '60 Hz', '90 Hz', '120 Hz', '144 Hz', '240 Hz'],
        'Automatic',
      ),
      toggle(
        'media.hdr',
        'Allow HDR',
        'Request HDR output when the display, GPU, provider, and codec support it.',
      ),
      select(
        'media.audioOutput',
        'Audio output',
        'Default output for game and browser audio.',
        ['System default', 'Headphones', 'Speakers', 'HDMI/Display'],
        'System default',
      ),
      select(
        'media.audioInput',
        'Microphone input',
        'Default microphone for voice chat and broadcasts.',
        ['System default', 'No microphone', 'Ask each time'],
        'System default',
      ),
      range(
        'media.gameVolume',
        'Game volume',
        'Volume for the active game or stream.',
        0,
        100,
        1,
        100,
        '%',
      ),
      range(
        'media.chatVolume',
        'Chat volume',
        'Relative volume for voice and chat channels.',
        0,
        100,
        1,
        100,
        '%',
      ),
      toggle(
        'media.spatialAudio',
        'Spatial audio',
        'Enable platform spatial-audio processing where available.',
      ),
      toggle(
        'media.micNoiseSuppression',
        'Microphone noise suppression',
        'Reduce background noise during voice chat and broadcasts.',
        true,
      ),
      toggle(
        'media.voiceChat',
        'Enable voice chat',
        'Join the session voice channel with the selected microphone when the host supports it. Microphone permission is requested explicitly during the session.',
      ),
      select(
        'media.recordingCodec',
        'Recording codec',
        'Codec used for local clips and recordings.',
        ['Automatic', 'AV1', 'VP9', 'H.264'],
        'Automatic',
      ),
      select(
        'media.recordingLocation',
        'Recording location',
        'Folder used for screenshots, clips, and recordings.',
        ['Videos/Spartan Gaming', 'Desktop', 'Ask each time', 'Custom folder'],
        'Videos/Spartan Gaming',
      ),
    ],
  },
  {
    id: 'sync',
    label: 'Profiles & sync',
    icon: '⇄',
    description: 'Profiles, encrypted settings, and cross-device continuity.',
    settings: [
      select(
        'sync.activeProfile',
        'Active profile',
        'Identity, cookies, permissions, saves, and library state are isolated by profile.',
        ['Default', 'Gaming', 'Family', 'Guest'],
        'Gaming',
      ),
      toggle(
        'sync.settings',
        'Sync settings',
        'Sync preferences across signed-in Spartan Gaming devices.',
      ),
      toggle(
        'sync.library',
        'Sync library and profiles',
        'Sync provider links, emulator profiles, controller mappings, and metadata.',
      ),
      toggle(
        'sync.saveData',
        'Sync save data',
        'Sync save RAM and save states using encrypted storage.',
      ),
      select(
        'sync.provider',
        'Sync provider',
        'Storage used for encrypted cross-device data.',
        ['Spartan Sync', 'Self-hosted sync', 'None'],
        'None',
      ),
      toggle(
        'sync.encryptLocally',
        'Encrypt synced data locally',
        'Require a local recovery key before sync data can be restored.',
        true,
      ),
      action(
        'sync.manageProfiles',
        'Manage profiles',
        'Create, rename, export, or remove browser and gaming profiles.',
        'Open profile manager',
      ),
      action(
        'sync.exportSettings',
        'Export settings',
        'Create a portable settings file without credentials or session cookies.',
        'Export settings',
      ),
      action(
        'sync.importSettings',
        'Import settings',
        'Restore settings and mappings from a portable file.',
        'Import settings',
      ),
    ],
  },
  {
    id: 'accessibility',
    label: 'Accessibility',
    icon: '⊙',
    description: 'Readable, remappable, and assistive gaming controls.',
    settings: [
      toggle(
        'accessibility.highContrast',
        'High contrast mode',
        'Increase control, text, and focus contrast.',
        false,
      ),
      toggle(
        'accessibility.largeText',
        'Large text',
        'Increase interface text and control labels.',
        false,
      ),
      select(
        'accessibility.colorVision',
        'Color vision mode',
        'Adjust status colors for common color-vision differences.',
        ['None', 'Protanopia', 'Deuteranopia', 'Tritanopia'],
        'None',
      ),
      toggle(
        'accessibility.focusRing',
        'Always show focus ring',
        'Keep keyboard and controller focus visible.',
        true,
      ),
      toggle(
        'accessibility.reduceMotion',
        'Reduce motion',
        'Disable non-essential animation and transition effects.',
        false,
      ),
      toggle(
        'accessibility.screenReaderHints',
        'Screen-reader hints',
        'Add context to complex game-session and controller controls.',
      ),
      toggle(
        'accessibility.stickyKeys',
        'Sticky modifier keys',
        'Allow modifier keys to be pressed sequentially.',
      ),
      toggle('accessibility.monoAudio', 'Mono audio', 'Mix stereo output into a single channel.'),
      select(
        'accessibility.captionMode',
        'Closed captions',
        'Show captions or subtitles when the active media surface provides text tracks.',
        ['Off', 'On'],
        'Off',
      ),
      select(
        'accessibility.captionLanguage',
        'Caption language',
        'Preferred caption or subtitle language; Automatic follows the media default.',
        ['Automatic', 'English', 'Spanish', 'French', 'German', 'Japanese'],
        'Automatic',
      ),
      select(
        'accessibility.touchLayout',
        'Touch-control layout',
        'Default virtual controller layout on touch devices.',
        ['Automatic', 'Minimal', 'Full gamepad', 'Custom'],
        'Automatic',
      ),
      action(
        'accessibility.remapShortcuts',
        'Remap browser shortcuts',
        'Configure keyboard, controller, switch, and voice shortcuts.',
        'Open shortcut editor',
      ),
    ],
  },
  {
    id: 'advanced',
    label: 'Advanced & developer',
    icon: '⌬',
    description: 'Experimental features, logs, protocols, and diagnostics.',
    settings: [
      toggle(
        'advanced.developerMode',
        'Developer mode',
        'Expose primary-window debugging tools and desktop developer shortcuts. Provider login and player surfaces remain isolated.',
      ),
      toggle(
        'advanced.experimentalWebTransport',
        'Experimental WebTransport',
        'Allow compatible self-hosted sessions to test WebTransport transport.',
      ),
      toggle(
        'advanced.experimentalUpscaling',
        'Experimental client upscaling',
        'Try client-side enhancement for supported stream formats.',
      ),
      toggle(
        'advanced.allowUnsignedAdapters',
        'Allow unsigned local adapters',
        'Load local development adapters without release signatures.',
      ),
      toggle(
        'advanced.verboseLogs',
        'Verbose logs',
        'Write detailed browser, provider, emulator, and session logs locally.',
      ),
      select(
        'advanced.logRetention',
        'Log retention',
        'How long local diagnostic logs are retained.',
        ['1 day', '7 days', '30 days', 'Until manually removed'],
        '7 days',
      ),
      toggle(
        'advanced.networkSimulation',
        'Network simulation tools',
        'Expose artificial latency, jitter, packet loss, and bandwidth controls.',
      ),
      toggle(
        'advanced.forceSoftwareDecode',
        'Force software video decode',
        'Useful for diagnosing GPU driver and hardware decoder issues.',
      ),
      text(
        'advanced.customSignalingUrl',
        'Custom signaling URL',
        'Endpoint for a self-hosted Spartan Host signaling service.',
        '',
      ),
      action(
        'advanced.exportDiagnostics',
        'Export diagnostics bundle',
        'Create a redacted local Electron diagnostics bundle without credentials or provider URLs.',
        'Export bundle',
      ),
      action(
        'advanced.clearDiagnostics',
        'Clear local diagnostics',
        'Remove every locally retained Electron crash and verbose-log entry.',
        'Clear diagnostics',
      ),
      action(
        'advanced.flags',
        'Open developer tools',
        'Inspect the local Spartan Gaming application renderer. Developer mode must be enabled first.',
        'Open developer tools',
      ),
    ],
  },
  {
    id: 'updates',
    label: 'Updates',
    icon: '↻',
    description: 'Signed standalone application release behavior.',
    settings: [
      select(
        'updates.channel',
        'Release channel',
        'Choose stable, beta, or alpha signed application releases.',
        ['Stable', 'Beta', 'Alpha'],
        'Stable',
      ),
      toggle(
        'updates.autoUpdate',
        'Automatically update Spartan Gaming',
        'Check the selected channel automatically and download verified application updates when available.',
        true,
      ),
      toggle(
        'updates.adapterUpdates',
        'Update adapters automatically',
        'Keep provider and emulator adapters current within the selected channel.',
        true,
      ),
      toggle(
        'updates.coreUpdates',
        'Update emulator cores automatically',
        'Update cores while preserving pinned versions and save compatibility.',
      ),
      toggle(
        'updates.catalogUpdates',
        'Update provider and game metadata',
        'Refresh compatibility, artwork, and capability metadata.',
        true,
      ),
      toggle(
        'updates.notifyRestart',
        'Notify before restart',
        'Ask before applying a downloaded update that restarts the application.',
        true,
      ),
      action(
        'updates.checkNow',
        'Check for updates',
        'Check the selected signed application release channel now.',
        'Check now',
      ),
      action(
        'updates.releaseNotes',
        'View release notes',
        'Review changes, known issues, and security fixes.',
        'View release notes',
      ),
    ],
  },
];

export const defaultSettings = Object.fromEntries(
  settingsCategories
    .flatMap((category) => category.settings)
    .filter((setting) => setting.type !== 'action')
    .map((setting) => [setting.key, setting.default]),
);
