import test from 'node:test';
import assert from 'node:assert/strict';
import {applyDeadzone, createInputEventEnvelope, createInputMapper, normalizeGamepadState} from './input.mjs';

test('deadzone suppresses drift and rescales live input', () => { assert.equal(applyDeadzone(0.1, 0.2), 0); assert.ok(Math.abs(applyDeadzone(0.6, 0.2) - 0.5) < 0.001); assert.equal(applyDeadzone(-2), -1); });
test('gamepad state is normalized and immutable', () => { const state = normalizeGamepadState({id: 'Pad', index: 1, buttons: [{pressed: true, value: 1}], axes: [0.1, -0.5], timestamp: 4}); assert.equal(state.buttons[0].pressed, true); assert.equal(state.axes[0], 0); assert.ok(state.axes[1] < 0); assert.equal(Object.isFrozen(state), true); });
test('input mapper emits stable action events', () => { const mapper = createInputMapper({bindings: {confirm: 'button-0', moveLeft: 'axis-0-negative'}}); assert.deepEqual(mapper.mapButton(0, true), {type: 'input.event', action: 'confirm', pressed: true, value: 1}); assert.equal(mapper.mapAxis(0, -0.8).action, 'moveLeft'); assert.equal(mapper.mapAxis(0, 0.03), null); });
test('input events become protocol envelopes without leaking extra fields', () => { const envelope = createInputEventEnvelope({sessionId: 'ses-input-01', sequence: 4, event: {type: 'input.event', action: 'confirm', pressed: true, value: 1, source: 'keyboard', control: 'Enter'}, clock: () => '2026-08-07T12:00:00.000Z'}); assert.equal(envelope.type, 'input.event'); assert.deepEqual(envelope.payload, {action: 'confirm', pressed: true, value: 1, source: 'keyboard', control: 'Enter'}); });
test('input envelopes preserve signed analog values', () => { const envelope = createInputEventEnvelope({sessionId: 'ses-input-02', event: {type: 'input.event', action: 'moveLeft', pressed: true, value: -0.8}}); assert.equal(envelope.payload.value, -0.8); });
