import {normalizeGamepadState} from './input.mjs';
import {BUILTIN_CONTROLLER_PROFILES} from './profiles.mjs';

export function inspectGamepad(gamepad, {deadzone = 0.12} = {}) {
  const state = normalizeGamepadState(gamepad, {deadzone});
  return Object.freeze({...state, haptics: Array.isArray(gamepad.vibrationActuators) && gamepad.vibrationActuators.length > 0, hand: gamepad.hand || 'unknown', mapping: gamepad.mapping || 'unknown', batteryLevel: Number.isFinite(gamepad.batteryLevel) ? Math.max(0, Math.min(1, gamepad.batteryLevel)) : null});
}

export function detectInputCapabilities({navigatorRef = globalThis.navigator} = {}) { return Object.freeze({gamepad: typeof navigatorRef?.getGamepads === 'function', hid: Boolean(navigatorRef?.hid?.getDevices), vibration: typeof navigatorRef?.vibrate === 'function'}); }

export function resolveControllerPreferences(settings = {}) { const profileNames = new Set(['Auto-detect', ...BUILTIN_CONTROLLER_PROFILES.map(profile => profile.name)]); return Object.freeze({defaultProfile: profileNames.has(settings['controllers.defaultProfile']) ? settings['controllers.defaultProfile'] : 'Auto-detect', allowGamepad: settings['controllers.allowGamepad'] !== false, allowHid: settings['controllers.allowHid'] === true, multipleControllers: settings['controllers.multipleControllers'] !== false, playerSlots: ['1', '2', '4', '8'].includes(settings['controllers.playerSlots']) ? Number(settings['controllers.playerSlots']) : 4, inputMode: ['Auto-detect', 'XInput', 'DirectInput', 'Standard Gamepad', 'HID passthrough'].includes(settings['controllers.inputMode']) ? settings['controllers.inputMode'] : 'Auto-detect', virtualGamepadBackend: ['Automatic', 'Browser Gamepad', 'Linux uinput', 'Windows external driver', 'macOS external driver', 'Disabled'].includes(settings['controllers.virtualGamepadBackend']) ? settings['controllers.virtualGamepadBackend'] : 'Automatic', hapticsBackend: ['Automatic', 'Browser vibration', 'Native rumble', 'Disabled'].includes(settings['controllers.hapticsBackend']) ? settings['controllers.hapticsBackend'] : 'Automatic', rumble: settings['controllers.rumble'] !== false, adaptiveTriggers: settings['controllers.adaptiveTriggers'] === true, gyro: settings['controllers.gyro'] === true, touchpad: settings['controllers.touchpad'] === true, backButtons: settings['controllers.backButtons'] === true, triggerMode: ['Analog and digital', 'Analog only', 'Digital only'].includes(settings['controllers.triggerMode']) ? settings['controllers.triggerMode'] : 'Analog and digital', steeringRange: Math.max(90, Math.min(1080, Number(settings['controllers.steeringRange']) || 900)), splitInput: settings['controllers.splitInput'] === true, inputPolling: ['Automatic', 'Standard', 'High frequency'].includes(settings['controllers.inputLatency']) ? settings['controllers.inputLatency'] : 'Automatic'}); }

export async function listApprovedHidDevices({navigatorRef = globalThis.navigator} = {}) { if (typeof navigatorRef?.hid?.getDevices !== 'function') return []; const devices = await navigatorRef.hid.getDevices(); return devices.map(device => Object.freeze({productName: String(device.productName || 'HID device'), vendorId: Number(device.vendorId) || 0, productId: Number(device.productId) || 0, opened: Boolean(device.opened)})); }
