import test from 'node:test';
import assert from 'node:assert/strict';
import {detectInputCapabilities, inspectGamepad, listApprovedHidDevices, resolveControllerPreferences} from './inspector.mjs';

test('gamepad inspector reports normalized controls and haptics', () => { const snapshot = inspectGamepad({id: 'Test pad', index: 0, mapping: 'standard', buttons: [{pressed: true, value: 1}], axes: [-0.8], vibrationActuators: [{}], batteryLevel: 0.75}); assert.equal(snapshot.buttons[0].pressed, true); assert.ok(snapshot.axes[0] < 0); assert.equal(snapshot.haptics, true); assert.equal(snapshot.batteryLevel, 0.75); });
test('input capability detection handles browser API absence', () => { assert.deepEqual(detectInputCapabilities({navigatorRef: {}}), {gamepad: false, hid: false, vibration: false}); });
test('approved HID devices are reduced to stable device metadata', async () => { const devices = await listApprovedHidDevices({navigatorRef: {hid: {getDevices: async () => [{productName: 'Wheel', vendorId: 10, productId: 20, opened: true}]}}}); assert.deepEqual(devices, [{productName: 'Wheel', vendorId: 10, productId: 20, opened: true}]); });
test('controller preferences normalize explicit profile, permissions, HID, and advanced controls', () => { const preferences = resolveControllerPreferences({'controllers.defaultProfile': 'DualSense Edge', 'controllers.allowGamepad': false, 'controllers.allowHid': true, 'controllers.multipleControllers': false, 'controllers.playerSlots': '8', 'controllers.inputMode': 'DirectInput', 'controllers.virtualGamepadBackend': 'Linux uinput', 'controllers.hapticsBackend': 'Native rumble', 'controllers.rumble': false, 'controllers.adaptiveTriggers': true, 'controllers.gyro': true, 'controllers.touchpad': true, 'controllers.backButtons': true, 'controllers.triggerMode': 'Analog only', 'controllers.steeringRange': 1080, 'controllers.splitInput': true, 'controllers.inputLatency': 'High frequency'}); assert.deepEqual(preferences, {defaultProfile: 'DualSense Edge', allowGamepad: false, allowHid: true, multipleControllers: false, playerSlots: 8, inputMode: 'DirectInput', virtualGamepadBackend: 'Linux uinput', hapticsBackend: 'Native rumble', rumble: false, adaptiveTriggers: true, gyro: true, touchpad: true, backButtons: true, triggerMode: 'Analog only', steeringRange: 1080, splitInput: true, inputPolling: 'High frequency'}); assert.equal(resolveControllerPreferences().defaultProfile, 'Auto-detect'); assert.equal(resolveControllerPreferences().allowGamepad, true); assert.equal(resolveControllerPreferences().rumble, true); });
test('controller preferences accept every Electron profile option', () => { assert.equal(resolveControllerPreferences({'controllers.defaultProfile': 'Nintendo layout'}).defaultProfile, 'Nintendo layout'); assert.equal(resolveControllerPreferences({'controllers.defaultProfile': 'Racing wheel and pedals'}).defaultProfile, 'Racing wheel and pedals'); });
