import test from 'node:test';
import assert from 'node:assert/strict';
import {chooseFocusIndex, focusFirstControl, readNavigationAction, readNavigationKey, syncRuntimeControllerNavigation} from './navigation.mjs';

const pad = (buttons, axes = []) => ({index: 0, buttons: Array.from({length: 16}, (_, index) => ({pressed: buttons.includes(index), value: buttons.includes(index) ? 1 : 0})), axes});
test('navigation actions emit only on button and axis rising edges', () => { assert.equal(readNavigationAction(pad([0])), 'confirm'); assert.equal(readNavigationAction(pad([0]), {buttons: [{pressed: true}]}), null); assert.equal(readNavigationAction(pad([], [-0.8])), 'left'); assert.equal(readNavigationAction(pad([], [-0.8]), {axes: [-0.8]}), null); });
test('television keyboard keys map to bounded navigation actions', () => { assert.equal(readNavigationKey({key: 'ArrowRight'}), 'right'); assert.equal(readNavigationKey({key: 'Enter'}), 'confirm'); assert.equal(readNavigationKey({key: 'BrowserBack'}), 'cancel'); assert.equal(readNavigationKey({key: 'Unrelated'}), null); });
test('focus navigation chooses the nearest control in the requested direction', () => { const elements = [{getBoundingClientRect: () => ({left: 0, top: 0, width: 10, height: 10})}, {getBoundingClientRect: () => ({left: 30, top: 0, width: 10, height: 10})}, {getBoundingClientRect: () => ({left: 0, top: 30, width: 10, height: 10})}]; assert.equal(chooseFocusIndex(elements, 0, 'right'), 1); assert.equal(chooseFocusIndex(elements, 0, 'down'), 2); });
test('television focus wrapping selects the opposite directional edge', () => { const elements = [{getBoundingClientRect: () => ({left: 0, top: 0, width: 10, height: 10})}, {getBoundingClientRect: () => ({left: 30, top: 0, width: 10, height: 10})}]; assert.equal(chooseFocusIndex(elements, 1, 'right', {wrap: true}), 0); assert.equal(chooseFocusIndex(elements, 0, 'left', {wrap: true}), 1); });
test('television navigation can establish the first focus target', () => { let focused = 0; const first = {focus() { focused += 1; }}; assert.equal(focusFirstControl([first]), first); assert.equal(focused, 1); assert.equal(focusFirstControl([]), null); });
test('runtime controller navigation is shared across pages and remains idempotent', () => { let scheduled = 0; let cleared = 0; const root = {documentElement: {dataset: {spartanNavigation: 'remote-controller'}}, querySelectorAll: () => [{focus() {}}]}; const options = {navigatorLike: {getGamepads: () => []}, scheduler: () => ++scheduled, clearScheduler: () => { cleared += 1; }}; const first = syncRuntimeControllerNavigation(root, options); const second = syncRuntimeControllerNavigation(root, options); assert.equal(first, second); assert.equal(scheduled, 1); root.documentElement.dataset.spartanNavigation = 'pointer-keyboard'; assert.equal(syncRuntimeControllerNavigation(root, options), null); assert.equal(cleared, 1); });
