import '../pwa/register.mjs';
import {BUILTIN_CONTROLLER_PROFILES, createControllerProfile, createControllerProfileStore, updateControllerBinding} from './profiles.mjs';

const store = createControllerProfileStore({storage: window.localStorage});
const controls = ['button-0', 'button-1', 'button-2', 'button-3', 'button-8', 'button-9', 'axis-0-negative', 'axis-0-positive', 'axis-1-negative', 'axis-1-positive', 'key-Enter', 'key-Escape', 'key-Tab', 'key-P'];
let profiles = [...BUILTIN_CONTROLLER_PROFILES, ...store.list()]; let active = profiles[0];
const list = document.querySelector('[data-profile-list]'); const bindings = document.querySelector('[data-bindings]'); const notice = document.querySelector('[data-notice]');
function toast(message) { notice.textContent = message; notice.classList.add('visible'); setTimeout(() => notice.classList.remove('visible'), 2300); }
function renderList() { list.innerHTML = profiles.map(profile => `<button class="profile-item ${profile.id === active.id ? 'active' : ''}" data-profile="${profile.id}"><strong>${profile.name}</strong><small>${profile.deviceMatch}</small></button>`).join(''); list.querySelectorAll('[data-profile]').forEach(button => button.addEventListener('click', () => { active = profiles.find(profile => profile.id === button.dataset.profile); render(); })); }
function renderEditor() { document.querySelector('[data-profile-name]').textContent = active.name; document.querySelector('[data-profile-match]').textContent = `Matches ${active.deviceMatch}`; document.querySelector('[data-name]').value = active.name; document.querySelector('[data-match]').value = active.deviceMatch; document.querySelector('[data-deadzone]').value = Math.round(active.deadzone * 100); document.querySelector('[data-deadzone-value]').textContent = `${Math.round(active.deadzone * 100)}%`; bindings.innerHTML = Object.entries(active.bindings).map(([action, control]) => `<div class="binding"><label>${action}</label><select data-binding="${action}">${controls.map(option => `<option ${option === control ? 'selected' : ''}>${option}</option>`).join('')}</select></div>`).join(''); bindings.querySelectorAll('[data-binding]').forEach(select => select.addEventListener('change', () => { try { active = updateControllerBinding(active, select.dataset.binding, select.value); renderEditor(); toast('Binding updated locally'); } catch (error) { toast(error.message); renderEditor(); } })); }
function render() { renderList(); renderEditor(); }
document.querySelector('[data-deadzone]').addEventListener('input', event => { active = createControllerProfile({...active, deadzone: Number(event.target.value) / 100}); document.querySelector('[data-deadzone-value]').textContent = `${event.target.value}%`; });
document.querySelector('[data-save]').addEventListener('click', () => { active = store.save({...active, name: document.querySelector('[data-name]').value, deviceMatch: document.querySelector('[data-match]').value, deadzone: Number(document.querySelector('[data-deadzone]').value) / 100}); profiles = [...BUILTIN_CONTROLLER_PROFILES, ...store.list().filter(profile => !BUILTIN_CONTROLLER_PROFILES.some(builtin => builtin.id === profile.id))]; render(); toast('Controller profile saved'); });
document.querySelector('[data-new]').addEventListener('click', () => { const id = `custom-${Date.now()}`; active = createControllerProfile({id, name: 'Custom profile'}); profiles = [...profiles, active]; render(); });
render();
