import test from 'node:test';
import assert from 'node:assert/strict';
import {BUILTIN_CONTROLLER_PROFILES, createControllerProfile, createControllerProfileStore, resolveControllerProfile, updateControllerBinding, validateBindings} from './profiles.mjs';

test('built-in profiles cover common controller families and are immutable', () => { assert.equal(BUILTIN_CONTROLLER_PROFILES.length, 17); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'xbox-elite-layout')); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'dualsense-edge-layout')); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'joy-con-layout')); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'steam-controller-layout')); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'racing-wheel-layout')); assert.ok(BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === 'flight-stick-layout')); assert.equal(Object.isFrozen(BUILTIN_CONTROLLER_PROFILES[0]), true); });
test('variant profiles preserve unique extra controls', () => { const elite = BUILTIN_CONTROLLER_PROFILES.find(profile => profile.id === 'xbox-elite-layout'); const edge = BUILTIN_CONTROLLER_PROFILES.find(profile => profile.id === 'dualsense-edge-layout'); assert.equal(elite.bindings.leftPaddle2, 'button-13'); assert.equal(edge.bindings.rightPaddle, 'button-16'); assert.equal(new Set(Object.values(elite.bindings)).size, Object.keys(elite.bindings).length); });
test('binding validation rejects collisions', () => { assert.throws(() => validateBindings({confirm: 'button-0', cancel: 'button-0'}), /already bound/); });
test('profile updates preserve metadata and reject accidental collisions', () => { const profile = createControllerProfile({id: 'test-pad', name: 'Test pad'}); const updated = updateControllerBinding(profile, 'confirm', 'button-4'); assert.equal(updated.bindings.confirm, 'button-4'); assert.throws(() => updateControllerBinding(updated, 'cancel', 'button-4'), /already bound/); });
test('profile store persists, replaces, and removes profiles', () => { const store = createControllerProfileStore(); store.save({id: 'pad', name: 'Pad'}); store.save({id: 'pad', name: 'Updated pad'}); assert.equal(store.list().length, 1); assert.equal(store.get('pad').name, 'Updated pad'); store.remove('pad'); assert.equal(store.get('pad'), undefined); });
test('profile store exports and imports portable controller configurations', () => { const values = new Map(); const storage = {getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value)}; const store = createControllerProfileStore({storage}); store.save({id: 'wheel', name: 'Wheel', deviceMatch: 'wheel', rumble: false}); const exported = store.export(); const restored = createControllerProfileStore({storage: {getItem: key => values.get(`restored:${key}`) || null, setItem: (key, value) => values.set(`restored:${key}`, value)}}); const profiles = restored.import(exported); assert.equal(profiles[0].id, 'wheel'); assert.equal(profiles[0].rumble, false); assert.equal(restored.get('wheel').deviceMatch, 'wheel'); assert.throws(() => restored.import(JSON.stringify({version: 2, profiles: []})), /unsupported/); assert.throws(() => restored.import(JSON.stringify({version: 1, profiles: [{id: 'dup', name: 'One'}, {id: 'dup', name: 'Two'}]})), /duplicate/); });
test('custom profiles override matching built-in profiles', () => { const custom = createControllerProfile({id: 'xbox-layout', name: 'My Xbox mapping', rumble: false}); assert.equal(resolveControllerProfile({profileId: 'xbox-layout', profiles: [custom]}), custom); });
test('automatic profile selection matches device names and prefers custom profiles', () => {
  const custom = createControllerProfile({id: 'my-dualsense', name: 'My DualSense', deviceMatch: 'Sony Wireless Controller', rumble: false});
  assert.equal(resolveControllerProfile({profileId: 'Auto-detect', deviceName: 'Sony Wireless Controller (USB)', profiles: [custom]}), custom);
  assert.equal(resolveControllerProfile({profileId: 'auto', deviceName: 'Xbox Elite Wireless Controller'}).id, 'xbox-elite-layout');
  assert.equal(resolveControllerProfile({profileId: 'auto', deviceName: 'Unlisted USB pad'}).id, 'generic-hid-layout');
});
