import '../pwa/register.mjs';
import {BUILTIN_CONTROLLER_PROFILES, CONTROLLER_PROFILE_CAPABILITIES, createControllerProfile, createControllerProfileStore, updateControllerBinding} from './profiles.mjs';
import {createActiveProfileStorage} from '../profiles/storage.mjs';

const store = createControllerProfileStore({storage: createActiveProfileStorage({storage: window.localStorage})});
const controls = [...Array.from({length: 32}, (_, index) => `button-${index}`), 'axis-0', 'axis-0-negative', 'axis-0-positive', 'axis-1', 'axis-1-negative', 'axis-1-positive', 'axis-2', 'axis-2-negative', 'axis-2-positive', 'axis-3', 'axis-3-negative', 'axis-3-positive', 'axis-4', 'axis-4-negative', 'axis-4-positive', 'axis-5', 'axis-5-negative', 'axis-5-positive', 'key-Enter', 'key-Escape', 'key-Tab', 'key-P', 'mouse-left', 'mouse-right', 'mouse-middle'];
const escapeHtml = value => String(value).replace(/[&<>\'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
function allProfiles() { const custom = store.list(); const customIds = new Set(custom.map(profile => profile.id)); return [...custom, ...BUILTIN_CONTROLLER_PROFILES.filter(profile => !customIds.has(profile.id))]; }
let profiles = allProfiles(); let active = profiles[0];
const list = document.querySelector('[data-profile-list]'); const bindings = document.querySelector('[data-bindings]'); const notice = document.querySelector('[data-notice]');
function toast(message) { notice.textContent = message; notice.classList.add('visible'); setTimeout(() => notice.classList.remove('visible'), 2300); }
function renderList() { list.innerHTML = profiles.map(profile => `<button class="profile-item ${profile.id === active.id ? 'active' : ''}" data-profile="${escapeHtml(profile.id)}"><strong>${escapeHtml(profile.name)}</strong><small>${escapeHtml(profile.deviceMatch)}</small></button>`).join(''); list.querySelectorAll('[data-profile]').forEach(button => button.addEventListener('click', () => { active = profiles.find(profile => profile.id === button.dataset.profile); render(); })); }
function renderEditor() { document.querySelector('[data-profile-name]').textContent = active.name; document.querySelector('[data-profile-match]').textContent = `Matches ${active.deviceMatch}`; document.querySelector('[data-name]').value = active.name; document.querySelector('[data-match]').value = active.deviceMatch; document.querySelector('[data-deadzone]').value = Math.round(active.deadzone * 100); document.querySelector('[data-deadzone-value]').textContent = `${Math.round(active.deadzone * 100)}%`; document.querySelector('[data-rumble]').checked = active.rumble; document.querySelector('[data-profile-capabilities]').innerHTML = active.capabilities.length ? active.capabilities.map(capability => `<span>${escapeHtml(capability)}</span>`).join('') : '<span>Runtime-detected features</span>'; document.querySelector('[data-capabilities-editor]').innerHTML = CONTROLLER_PROFILE_CAPABILITIES.map(capability => `<label class="check capability-option"><input type="checkbox" data-capability="${escapeHtml(capability)}" ${active.capabilities.includes(capability) ? 'checked' : ''}>${escapeHtml(capability)}</label>`).join(''); document.querySelector('[data-remove]').disabled = BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === active.id); bindings.innerHTML = Object.entries(active.bindings).map(([action, control]) => `<div class="binding"><label>${escapeHtml(action)}</label><select data-binding="${escapeHtml(action)}">${controls.map(option => `<option ${option === control ? 'selected' : ''}>${escapeHtml(option)}</option>`).join('')}</select></div>`).join(''); bindings.querySelectorAll('[data-binding]').forEach(select => select.addEventListener('change', () => { try { active = updateControllerBinding(active, select.dataset.binding, select.value); renderEditor(); toast('Binding updated locally'); } catch (error) { toast(error.message); renderEditor(); } })); }
function render() { renderList(); renderEditor(); }
document.querySelector('[data-deadzone]').addEventListener('input', event => { active = createControllerProfile({...active, deadzone: Number(event.target.value) / 100}); document.querySelector('[data-deadzone-value]').textContent = `${event.target.value}%`; });
document.querySelector('[data-save]').addEventListener('click', () => { const capabilities = [...document.querySelectorAll('[data-capability]:checked')].map(input => input.dataset.capability); active = store.save({...active, name: document.querySelector('[data-name]').value, deviceMatch: document.querySelector('[data-match]').value, deadzone: Number(document.querySelector('[data-deadzone]').value) / 100, rumble: document.querySelector('[data-rumble]').checked, capabilities}); profiles = allProfiles(); render(); toast('Controller profile saved'); });
document.querySelector('[data-new]').addEventListener('click', () => { const id = `custom-${Date.now()}`; active = createControllerProfile({id, name: 'Custom profile'}); profiles = [...profiles, active]; render(); });
function downloadProfiles() { const blob = new Blob([store.export()], {type: 'application/json'}); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'spartan-gaming-controller-profiles.json'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); }
document.querySelector('[data-export]').addEventListener('click', downloadProfiles);
document.querySelector('[data-remove]').addEventListener('click', () => { if (BUILTIN_CONTROLLER_PROFILES.some(profile => profile.id === active.id)) return; store.remove(active.id); profiles = allProfiles(); active = profiles[0]; render(); toast('Custom controller profile deleted'); });
document.querySelector('[data-import]').addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; try { store.import(await file.text()); profiles = allProfiles(); active = profiles.find(profile => profile.id === store.list()[0]?.id) || profiles[0]; render(); toast('Controller profiles imported'); } catch (error) { toast(`Profile import rejected: ${error.message}`); } event.target.value = ''; });
render();
