import assert from 'node:assert/strict';
import test from 'node:test';
import {createLaunchHistoryStore} from './history.mjs';

function storage() { const values = new Map(); return {setItem: (key, value) => values.set(key, value), getItem: key => values.get(key), removeItem: key => values.delete(key)}; }

test('launch history deduplicates and bounds recent backend records', () => { const store = createLaunchHistoryStore({storage: storage(), maxEntries: 2}); store.record({backendId: 'one', backendType: 'provider', name: 'One', mode: 'browser-first', action: 'open-url', at: '2026-08-07T00:00:00Z'}); store.record({backendId: 'two', backendType: 'emulator', name: 'Two', mode: 'native', action: 'choose-runtime', at: '2026-08-07T00:01:00Z'}); store.record({backendId: 'one', backendType: 'provider', name: 'One', mode: 'browser-first', action: 'open-url', at: '2026-08-07T00:02:00Z'}); assert.deepEqual(store.list().map(item => item.backendId), ['one', 'two']); assert.equal(store.list()[0].launchedAt, '2026-08-07T00:02:00Z'); });
test('launch history stores no arbitrary URL or credential fields', () => { const store = createLaunchHistoryStore({storage: storage()}); store.record({backendId: 'provider', backendType: 'provider', name: 'Provider', mode: 'browser-first', action: 'open-url', url: 'https://example.test', token: 'secret', at: '2026-08-07T00:00:00Z'}); assert.deepEqual(Object.keys(store.list()[0]).sort(), ['action', 'backendId', 'backendType', 'launchedAt', 'mode', 'name']); });
test('launch history rejects malformed records', () => { const store = createLaunchHistoryStore({storage: storage()}); assert.throws(() => store.record({backendId: 'provider'}), /backendType/); });
test('launch history exposes the newest safe record for resume surfaces', () => { const store = createLaunchHistoryStore({storage: storage()}); assert.equal(store.latest(), null); store.record({backendId: 'provider', backendType: 'provider', name: 'Provider', mode: 'browser-first', action: 'open-url', at: '2026-08-07T00:00:00Z'}); assert.deepEqual(store.latest(), {backendId: 'provider', backendType: 'provider', name: 'Provider', mode: 'browser-first', action: 'open-url', launchedAt: '2026-08-07T00:00:00Z'}); });
