import {collectCapabilities, redactDiagnostics} from './capabilities.mjs';

let report = null; const capabilityContainer = document.querySelector('[data-capabilities]'); const recommendationContainer = document.querySelector('[data-recommendation-list]');
const labels = {transports: {webrtc: 'WebRTC', webtransport: 'WebTransport', websocket: 'WebSocket'}, graphics: {webgpu: 'WebGPU', webgpuAdapter: 'WebGPU adapter', webgl: 'WebGL'}, input: {gamepad: 'Gamepad API', hid: 'WebHID'}, media: {hardwareDecodeApi: 'Hardware decode API', mediaDevices: 'Media devices'}, codecs: {h264: 'H.264', vp9: 'VP9', av1: 'AV1', opus: 'Opus'}};
function flattenCapabilities(value) { const cards = []; for (const group of ['transports', 'graphics', 'input']) for (const [key, status] of Object.entries(value[group] || {})) cards.push({group, key, label: labels[group]?.[key] || key, status: typeof status === 'boolean' ? status : null}); for (const [key, status] of Object.entries(value.media || {})) { if (key === 'codecs') for (const [codec, supported] of Object.entries(status)) cards.push({group: 'codecs', key: codec, label: labels.codecs[codec] || codec, status: Boolean(supported)}); else if (key === 'hardwareDecode') for (const [codec, result] of Object.entries(status)) cards.push({group: 'hardware decode', key: `hardware-${codec}`, label: `${labels.codecs[codec] || codec} hardware decode`, status: result.powerEfficient ? true : result.supported ? null : false}); else cards.push({group: 'media', key, label: labels.media?.[key] || key, status: typeof status === 'boolean' ? status : null}); } return cards; }
function render() {
  const capabilities = flattenCapabilities(report); capabilityContainer.innerHTML = capabilities.map(item => { const optional = ['webtransport', 'webgpuAdapter', 'hid', 'hardwareDecodeApi', 'mediaDevices', 'av1', 'vp9', 'opus'].includes(item.key) || item.group === 'hardware decode'; const statusClass = item.status === false ? optional ? 'warn' : 'bad' : item.status === null ? 'warn' : ''; return `<article class="cap-card"><div><h3>${item.label}</h3><p>${item.group.toUpperCase()} · ${item.status === null ? 'Supported; efficiency unknown' : item.status ? 'Detected and available' : 'Not detected'}</p></div><span class="cap-status ${statusClass}">${item.status === false ? '!' : item.status === null ? '—' : '✓'}</span></article>`; }).join(''); recommendationContainer.innerHTML = report.recommendations.length ? report.recommendations.map(item => `<div class="recommendation"><strong class="${item.severity}">${item.severity}</strong><span>${item.message}</span></div>`).join('') : '<div class="recommendation"><strong class="info">Ready</strong><span>No compatibility warnings were detected.</span></div>';
  const errors = report.recommendations.filter(item => item.severity === 'error').length; const warnings = report.recommendations.filter(item => item.severity === 'warning').length; document.querySelector('[data-summary-title]').textContent = errors ? `${errors} blocking issue${errors === 1 ? '' : 's'} detected` : warnings ? `${warnings} compatibility note${warnings === 1 ? '' : 's'}` : 'Ready for compatible sessions'; document.querySelector('[data-summary-copy]').textContent = `${report.browser.engine} · ${report.browser.platform} · checked ${new Date(report.collectedAt).toLocaleTimeString()}`;
}
async function run() { document.querySelector('[data-summary-title]').textContent = 'Checking capabilities…'; report = await collectCapabilities(); render(); }
document.querySelector('[data-run]').addEventListener('click', run);
document.querySelector('[data-export]').addEventListener('click', () => { if (!report) return; const blob = new Blob([JSON.stringify(redactDiagnostics(report), null, 2)], {type: 'application/json'}); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'spartan-gaming-diagnostics.json'; link.click(); URL.revokeObjectURL(link.href); });
run();
