#!/usr/bin/env node
import { readFile, writeFile, chmod } from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import path from 'node:path';

function text(value) {
  return typeof value === 'string' ? value.trim() : '';
}
function required(value, name) {
  const result = text(value);
  if (!result) throw new TypeError(`${name} is required`);
  return result;
}
function port(value, fallback, name) {
  const result = value === undefined ? fallback : Number(value);
  if (!Number.isInteger(result) || result < 1 || result > 65535)
    throw new RangeError(`${name} must be between 1 and 65535`);
  return result;
}
function secret(value) {
  const result = required(value, 'TURN shared secret');
  if (result.length < 32)
    throw new RangeError('TURN shared secret must contain at least 32 characters');
  return result;
}
function filePath(value, name) {
  return path.resolve(required(value, name));
}
function address(value) {
  const result = text(value);
  if (!result) return '';
  if (/[\r\n]/.test(result) || /\s/.test(result))
    throw new TypeError('TURN external address must be a single host or address');
  return result;
}

export function normalizeTurnRelayOptions({
  realm = 'spartan-gaming',
  listenPort = 3478,
  tlsPort = 5349,
  minPort = 49152,
  maxPort = 65535,
  externalIp,
  tlsCert,
  tlsKey,
} = {}) {
  const normalized = {
    realm: required(realm, 'TURN realm'),
    listenPort: port(listenPort, 3478, 'TURN listening port'),
    tlsPort: port(tlsPort, 5349, 'TURN TLS port'),
    minPort: port(minPort, 49152, 'TURN relay minimum port'),
    maxPort: port(maxPort, 65535, 'TURN relay maximum port'),
    externalIp: address(externalIp),
  };
  if (normalized.minPort > normalized.maxPort)
    throw new RangeError('TURN relay minimum port must not exceed maximum port');
  if (normalized.listenPort === normalized.tlsPort)
    throw new RangeError('TURN listening and TLS ports must differ');
  if ((tlsCert && !tlsKey) || (!tlsCert && tlsKey))
    throw new TypeError('TURN TLS certificate and key must be supplied together');
  if (tlsCert) {
    normalized.tlsCert = filePath(tlsCert, 'TURN TLS certificate path');
    normalized.tlsKey = filePath(tlsKey, 'TURN TLS key path');
  }
  return Object.freeze(normalized);
}

export function renderTurnServerConfig({ sharedSecret, options } = {}) {
  const normalizedSecret = secret(sharedSecret);
  const config = normalizeTurnRelayOptions(options);
  const lines = [
    '# Generated by Spartan Gaming; keep this file mode 0600.',
    `realm=${config.realm}`,
    `listening-port=${config.listenPort}`,
    `tls-listening-port=${config.tlsPort}`,
    'fingerprint',
    'lt-cred-mech',
    'use-auth-secret',
    `static-auth-secret=${normalizedSecret}`,
    'stale-nonce=600',
    `min-port=${config.minPort}`,
    `max-port=${config.maxPort}`,
    'no-cli',
    'no-loopback-peers',
    'no-multicast-peers',
    'no-tlsv1',
    'no-tlsv1_1',
  ];
  if (config.externalIp) lines.push(`external-ip=${config.externalIp}`);
  if (config.tlsCert) lines.push(`cert=${config.tlsCert}`, `pkey=${config.tlsKey}`);
  return Object.freeze({
    config: lines.join('\n') + '\n',
    options: config,
    secretMaterial:
      'embedded only in returned config; never log or persist without operator intent',
  });
}

export async function writeTurnServerConfig({
  sharedSecret,
  options,
  outputPath,
  fsImpl = { writeFile, chmod },
} = {}) {
  const destination = filePath(outputPath, 'TURN config output path');
  const rendered = renderTurnServerConfig({ sharedSecret, options });
  await fsImpl.writeFile(destination, rendered.config, { encoding: 'utf8', mode: 0o600 });
  await fsImpl.chmod(destination, 0o600);
  return Object.freeze({ status: 'written', outputPath: destination, options: rendered.options });
}

function argument(argv, name) {
  const index = argv.indexOf(name);
  return index < 0 ? '' : argv[index + 1];
}
if (path.resolve(process.argv[1] || '') === path.resolve(new URL(import.meta.url).pathname)) {
  try {
    const argv = process.argv.slice(2);
    const secretPath = filePath(argument(argv, '--secret-file'), 'TURN secret file');
    const sharedSecret = text(readFileSync(secretPath, 'utf8'));
    const result = await writeTurnServerConfig({
      sharedSecret,
      outputPath: argument(argv, '--output'),
      options: {
        realm: argument(argv, '--realm') || 'spartan-gaming',
        externalIp: argument(argv, '--external-ip'),
        tlsCert: argument(argv, '--tls-cert'),
        tlsKey: argument(argv, '--tls-key'),
      },
    });
    console.log(JSON.stringify(result));
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
